 <div class="sub-header-breadcrumb">
     <a href="<?php echo $this->url('home') ?>"><span class="home"></span></a>    
     <?php
     // iterate through the pages
    
     foreach ($this->pages as $key => $page):
         ?>
            <span class="breadcrumb-arrow"> > </span>
             <?php
             // if this isn't the last page, add a link and the separator
             if ($key < count($this->pages) - 1):
                 ?>
                 <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
             <?php
             // otherwise, just output the name
             else:
             ?>
                 <span><?php echo $page->getLabel(); ?></span>
             <?php endif; ?>
         
         <?php endforeach; ?>
 </div>