<?php
if (isset($_SESSION['User']['roleCode'])):
    $roleCode = $_SESSION['User']['roleCode'];
endif;
?>
<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
            <?php
            $title = 'View Package';
            $this->headTitle($title);
            ?>
            <a class="back-icon" href="<?php echo $this->url('package', array('action' => 'index')); ?>"></a>

            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>

                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
            </h1>
        </div>
    </div>
</section>

<div class="container">
    <div class="forms">
        <section class="profile-details center-details">
            <div class="short_profile_left">
                <ul>
                    <li class="name detail-row">
                        <?php echo $package[0]['title']; ?>
                        <span class="separator-img"></span>
                        <?php if ($package[0]['status'] == '1') { ?>
                            <span class="green-circle-status"></span>
                            <span class="status">        
                                <?php echo 'ACTIVE'; ?>
                            </span>
                        <?php } else { ?>
                            <span class="red-circle-status"></span>
                            <span class="status">        
                                <?php echo 'IN-ACTIVE'; ?>
                            </span>
                        <?php } ?>
                    </li>
                    <li class="nid detail-row">
                        <span class="nid-icon" title="Code"></span><span class="detail"> CODE : <?php echo $package[0]['code']; ?></span>
                    </li>
                    <li class="nid detail-row">
                        <span class="nid-icon" title="Description"></span><span class="detail"> DESCRIPTION : <?php echo $package[0]['description']; ?></span>
                    </li>
                    <li class="nid detail-row">
                        <span class="nid-icon" title="Duration"></span><span class="detail"> DURATION : <?php echo $package[0]['duration'] ?></span>
                    </li>
                    <li class="nid detail-row">
                        <span class="nid-icon" title="Price"></span><span class="detail"> PRICE : <?php echo $package[0]['price'] ?></span>
                    </li>
                    <li class="nid detail-row">
                        <span class="nid-icon" title="Face to Face Class-room"></span><span class="detail"> FACE TO FACE CLASSROOM : <?php echo $package[0]['ff_classroom'] ?></span>
                    </li>
                    <li class="nid detail-row">
                        <span class="nid-icon" title="relevant for"></span><span class="detail"> RELEVANT FOR : <?php
                            if (!empty($package[0]['relevant_for'])) {
                                $userGetsArr = explode(',', $package[0]['relevant_for']);
                                echo '<br/>';
                                echo '<ul>';
                                foreach ($userGetsArr as $gets) {
                                    echo '<li>';
                                    echo $gets;
                                    echo '</li>';
                                }
                                echo '</ul>';
                            }
                            ?></span>
                    </li>
                    <li class="nid detail-row">
                        <span class="nid-icon" title="advantage"></span><span class="detail"> ADVANTAGE : <?php
                            if (!empty($package[0]['advantage'])) {
                                $userGetsArr = explode(',', $package[0]['advantage']);
                                echo '<br/>';
                                echo '<ul>';
                                foreach ($userGetsArr as $gets) {
                                    echo '<li>';
                                    echo $gets;
                                    echo '</li>';
                                }
                                echo '</ul>';
                            }
                            ?></span>
                    </li>
                    <li class="nid detail-row">
                        <span class="nid-icon" title="what user gets"></span><span class="detail"> WHAT USER GETS : <?php
                            if (!empty($package[0]['whatuserget'])) {
                                $userGetsArr = explode(',', $package[0]['whatuserget']);
                                echo '<br/>';
                                echo '<ul>';
                                foreach ($userGetsArr as $gets) {
                                    echo '<li>';
                                    echo $gets;
                                    echo '</li>';
                                }
                                echo '</ul>';
                            }
                            ?></span>
                    </li>
                    <li class="nid detail-row">
                        <?php
                        if ($package[0]['image_path']) {
                            $packagePathArr = explode('/', $package[0]['image_path']);
                            foreach ($packagePathArr as $imageName) {
                                $imageFile = $imageName;
                            }
                            ?>
                            <img alt="Subject Image" src="<?php echo $_SESSION['basedomain']['path'] . '/data/images/' . $imageFile; ?>" style="height:auto; width: 25%;border-radius: 50%;"/>
                        <?php } ?>
                    </li>
                </ul>  
            </div> 
        </section>
        <div class="view-data-divider"></div>

        <section class="view-detail">
            <table border="1" class="table center-listing" id="option_table">
                <thead>
                    <tr>
                        <th class="fname"><input type='hidden' id='action' value='add'><?php echo $this->escapeHtml('COURSE NAME'); ?></th></tr>
                </thead>
                <tbody>
                    <?php
                    $i = 0;
                    foreach ($courseMapData as $map) {
                        ?>
                        <tr id="<?php echo $i; ?>">
                            <td class='fname'><input type='hidden' name='courseId[]' value="<?php echo $map['course_id']; ?>"/><?php echo $map['title']; ?></td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>
                </tbody>
            </table>
        </section>
    </div>
    <div id="form-footer">
    </div>
</div>









