<?php
$this->inlineScript()->appendFile($this->basePath() . '/js/koolguru/question/question.js');
$this->inlineScript()->appendFile($this->basePath() . '/js/koolguru/ckeditor/ckeditor.js');
$form = $this->form;
$form->setAttribute('action', $this->url('question', array('action' => 'edit', 'id' => $id, 'page' => $page)));
$form->setAttribute('class', 'detect_changes');
$form->prepare();
echo $this->form()->openTag($form);
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
?>
<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
            <?php
            $title = 'Edit Question';
            $this->headTitle($title);
            ?>
            <a class="back-icon" href="<?php echo $this->url('question', array('action' => 'index')); ?>"></a>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>
                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
                <?php //echo $this->content; ?>

            </h1>
        </div>
        <div class="sub-header-actions"></div>
    </div>
</section>

<div class="container">
    <div class="forms" id="add-trainee-form">
        <?php
        $errorflashMessage = $this->flashMessenger()->getErrorMessages();
        $successflashMessage = $this->flashMessenger()->getCurrentSuccessMessages();
        if (empty($errorflashMessage) && !empty($successflashMessage)) {
            ?>
            <div id="global-success-msg-page" class="global-page-success">
                <?php
                foreach ($successflashMessage as $succMsg) {
                    echo $succMsg;
                }
                ?>

            </div>
        <?php } else { ?>
            <div id="global-error-msg-page"   class="global-page-error"><?php
                foreach ($errorflashMessage as $errMsg) {
                    echo $errMsg;
                }
                ?></div>
        <?php } ?>
        <div class="upper-submit">
            <?php
            echo $this->formSubmit($form->get('submit'));
            ?>
        </div>
        <div id="step1">
            <section id="basic_details">
                <?php
                echo "<h2 class='h2'>Basic Details</h2>";
                echo $this->formHidden($form->get('id'));
                ?>

                <ul>
                    <li class="form-row">                    
                        <label class='label'>QUESTION NAME: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('name')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>DESCRIPTION: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('description')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>MINIMUM MARKS: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('min_marks')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>MAXIMUM MARKS: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('max_marks')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>LEVEL: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('level')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>TYPE: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('type')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>CATEGORY: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('category_id')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>IS ACTIVE: </label>
                        <?php echo $this->formElement($form->get('status')); ?>
                    </li>
                </ul>
            </section>
        </div>
        <div id="step2">
            <section id="basic_details">
                <?php
                echo "<h2 class='h2'>Add Options</h2>";
                ?>
                <ul>
                    <li class="form-row">                    
                        <label class='label'>OPTION DESCRIPTION: </label>
                        <?php echo $this->formElement($form->get('question_desc')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>IS CORRECT: </label>
                        <?php echo $this->formElement($form->get('is_correct')); ?>
                    </li>
                    <li class="form-row">
                        <a href="javascript:void(0)" class="green-btn big-btn" id="add_option">Add Option</a>
                    </li>
                </ul>
            </section>
            <table border="1" class="table center-listing" id="option_table">
                <thead>
                    <tr>
                        <th class="fname"><input type='hidden' id='action' value='add'><?php echo $this->escapeHtml('OPTION DESCRIPTION'); ?></th>
                        <th class="lname"><input type='hidden' id='qual_name' value=''><?php echo $this->escapeHtml('IS CORRECT'); ?></th>
                        <th class="actions"><?php echo $this->escapeHtml('ACTION'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $i = 0;
                    foreach ($questionOptions as $option) {
                        ?>
                        <tr id="<?php echo $i; ?>">
                            <td class='fname'><input type='hidden' name='option_description[]' value="<?php echo $option['description']; ?>"/><?php echo $option['description']; ?></td>
                            <td class='lname'><input type='hidden' name='option_correct[]' value="<?php echo $option['is_correct']; ?>"/><?php echo $option['is_correct'] == 0 ? 'No' : 'Yes'; ?></td>
                            <td><a href='javascript:void(0)' class='btnDelete delete-icon' onclick="DeleteRow('<?php echo $i; ?>')" id='row_<?php echo $i; ?>' title='delete'></a></td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>
                </tbody>
            </table>
        </div>
        <div class="form-footer text-center">
            <?php
            echo $this->formRow($form->get('previous'));
            echo $this->formRow($form->get('next'));
            ?>
        </div>
        <?php
        echo $this->formHidden($form->get('created_date'));
        echo $this->formHidden($form->get('created_by'));
        echo $this->formHidden($form->get('updated_date'));
        echo $this->formHidden($form->get('updated_by'));
        ?>
        <div id="form-footer">
            <?php
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
<script>
    CKEDITOR.on( 'instanceReady', function( evt ) {
			var editor = evt.editor;
			//editor.setData( 'This editor has it\'s tabIndex set to <strong>' + editor.tabIndex + '</strong>' );

			// Apply focus class name.
			editor.on( 'focus', function() {
				editor.container.addClass( 'cke_focused' );
			});
			editor.on( 'blur', function() {
				editor.container.removeClass( 'cke_focused' );
			});

			// Put startup focus on the first editor in tab order.
			if ( editor.tabIndex == 1 )
				editor.focus();
		});
    </script>