<?php
$this->inlineScript()->appendFile($this->basePath() . '/js/koolguru/quiz/quiz.js');
$form = $this->form;
$form->setAttribute('action', $this->url('quiz', array('action' => 'add')));
$form->setAttribute('class', 'detect_changes');
$form->prepare();
echo $this->form()->openTag($form);
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
?>
<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
            <?php
            $title = 'Create Quiz';
            ?>
            <a class="back-icon" href="<?php echo $this->url('quiz', array('action' => 'index')); ?>"></a>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>
                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
                <?php //echo $this->content; ?>

            </h1>
        </div>
        <div class="sub-header-actions"></div>
    </div>
</section>

<div class="container">
    <div class="forms" id="add-trainee-form">
        <?php
        $errorflashMessage = $this->flashMessenger()->getCurrentErrorMessages();
        $successflashMessage = $this->flashMessenger()->getCurrentSuccessMessages();
        if (empty($errorflashMessage) && !empty($successflashMessage)) {
            ?>
            <div id="global-success-msg-page" class="global-page-success">
                <?php
                foreach ($successflashMessage as $succMsg) {
                    echo $errMsg;
                }
                ?>

            </div>
            <?php
        } else {
            if (!empty($errorflashMessage)) {
                ?>
                <div id="global-error-msg-page"   class="global-page-error"><?php
                    foreach ($errorflashMessage as $errMsg) {
                        echo $errMsg;
                    }
                    ?></div>
                <?php
            }
        }
        ?>
<!--        <div class="upper-submit">
            <?php
            //echo $this->formSubmit($form->get('submit'));
            ?>
        </div>-->
        <div id="step1">
            <section id="basic_details">
                <?php
                echo $this->formHidden($form->get('id'));
                ?>

                <ul>
                    <li class="form-row">                    
                        <label class='label'>Title: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('title')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Subject: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('subject_id')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Chapter: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('chapter_id')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Code: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('code')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>DESCRIPTION: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('description')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Passing Percentage: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('pass_percentage')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Start Time: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('start_time')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>End Time: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('end_time')); ?>
                    </li>                    
                    <li class="form-row">                    
                        <label class='label'>IS ACTIVE: </label>
                        <?php echo $this->formElement($form->get('status')); ?>
                    </li>
                    <li class="form-row">                    
                        <div class="pull-left width-100">
						<div>Question Level</div> 
						<select name="chapter_id" id="chapter_id">
                            <option value="">Select</option>
                        </select>
						</div>
                        <div class="pull-left width-100">
						<div>Question Count</div>
						<input type="text" id="count">
                        </div>
						<div class="pull-left width-100">
						<div>Category</div>
						<select name="chapter_id" id="chapter_id">
                            <option value="">Select</option>
                        </select>
						</div>
						<div class="pull-left"> <div class="add-icon"></div></div>
						<div class="pull-left"><div class="delete-icon"></div></div>

                    </li>
                </ul>
            </section>
        </div>
        
        
        <?php
        echo $this->formHidden($form->get('created_at'));
        echo $this->formHidden($form->get('created_by'));
        echo $this->formHidden($form->get('updated_at'));
        echo $this->formHidden($form->get('updated_by'));
        ?>
        <div id="form-footer">
            <?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
    
    $('#subject_id').change(function(){
        var subject = $(this).val();        
        var url = '<?php echo $this->basePath() . '/quiz/getchapter?subject='; ?>' + subject;
        
        $.ajax({url: url, success: function (result) {
                var html = '<option value="">Select</option>';
                
                $.each(JSON.parse(result), function(idx, obj) {
                    
                    html += "<option value='"+obj.chapter_id+"'>"+obj.chaptertitle+"</option>";
                });
                $('#chapter_id').html(html);
        }});
    });
    });
    </script>