<?php
$this->inlineScript()->appendFile($this->basePath() . '/js/koolguru/quiz/quiz.js');
$form = $this->form;
$form->setAttribute('action', $this->url('quiz', array('action' => 'add')));
$form->setAttribute('class', 'detect_changes');
$form->prepare();
echo $this->form()->openTag($form);
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
?>
<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
            <?php
            $title = 'Create Quiz';
            ?>
            <a class="back-icon" href="<?php echo $this->url('quiz', array('action' => 'index')); ?>"></a>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>
                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
                <?php //echo $this->content; ?>

            </h1>
        </div>
        <div class="sub-header-actions"></div>
    </div>
</section>

<div class="container">
    <div class="forms" id="add-trainee-form">
        <?php
        $errorflashMessage = $this->flashMessenger()->getCurrentErrorMessages();
        $successflashMessage = $this->flashMessenger()->getCurrentSuccessMessages();
        if (empty($errorflashMessage) && !empty($successflashMessage)) {
            ?>
            <div id="global-success-msg-page" class="global-page-success">
                <?php
                foreach ($successflashMessage as $succMsg) {
                    echo $errMsg;
                }
                ?>

            </div>
            <?php
        } else {
            if (!empty($errorflashMessage)) {
                ?>
                <div id="global-error-msg-page"   class="global-page-error"><?php
                    foreach ($errorflashMessage as $errMsg) {
                        echo $errMsg;
                    }
                    ?></div>
                <?php
            }
        }
        ?>
<!--        <div class="upper-submit">
            <?php
            //echo $this->formSubmit($form->get('submit'));
            ?>
        </div>-->
        <div id="step1">
            <section id="basic_details">
                <?php
                echo $this->formHidden($form->get('id'));
                ?>

                <ul>
                    <li class="form-row">                    
                        <label class='label'>Title: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('title')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Subject: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('subject_id')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Chapter: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('chapter_id')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Code: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('code')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>DESCRIPTION: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('description')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Passing Percentage: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('pass_percentage')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Start Time: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('start_time')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>End Time: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('end_time')); ?>
                    </li>                    
                    <li class="form-row">                    
                        <label class='label'>IS ACTIVE: </label>
                        <?php echo $this->formElement($form->get('status')); ?>
                    </li>
                    <li class="form-row">
                        <div class="quiz-level" row="1">
                            <div class="pull-left width-100">
                                <div>Question Level</div> 
                                <select class="levl" name="level_1" id="level_1">
                                    <option value="">Select</option>
                                    <?php foreach($levelList as $k=>$v){?>
                                        <option value="<?php echo $k;?>"><?php echo $v;?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="pull-left width-100 quiz-left">
                                <div>Question Count</div>
                                    <input type="text" id="count_1" class="quecount text-height" name="count_1">
                            </div>
                            <div class="pull-left width-100 quiz-left">
                                <div>Category</div>
                                <select class="quecategory" name="category_1" id="category_1">
                                    <option value="">Select</option>
                                    <?php foreach($que_category as $k=>$v){?>
                                        <option value="<?php echo $k;?>"><?php echo $v;?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="pull-left quiz-left"> 
                                <div class="add-icon" id="addrow"></div>
                            </div>
                            <div class="pull-left quiz-left">
                                <div class="delete-icon"></div>                                    
                            </div>
                        </div>
                    </li>
                </ul>
            </section>
        </div>
        
        
        <?php
        echo $this->formHidden($form->get('created_at'));
        echo $this->formHidden($form->get('created_by'));
        echo $this->formHidden($form->get('updated_at'));
        echo $this->formHidden($form->get('updated_by'));
        ?>
        <div id="form-footer">
            <?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#addrow').click(function(){
            addnewrow(this)
        });
    
        $('#subject_id').change(function(){
            var subject = $(this).val();        
            var url = '<?php echo $this->basePath() . '/quiz/getchapter?subject='; ?>' + subject;

            $.ajax({url: url, success: function (result) {
                    var html = '<option value="">Select</option>';

                    $.each(JSON.parse(result), function(idx, obj) {

                        html += "<option value='"+obj.chapter_id+"'>"+obj.chaptertitle+"</option>";
                    });
                    $('#chapter_id').html(html);
            }});
        });
    });
    
    function addnewrow(obj){
        var clone = $(obj).parent().parent().clone();
        $(obj).parent().parent().parent().append('</br></br></br></br>');
        $(obj).parent().parent().parent().append(clone);
        manageRows();
    }
    
    function manageRows(){
        var i = 1;
        $('.quiz-level').each(function(){
            $(this).attr('row',i);
            $(this).find('.levl').attr('name','level_'+i);
            $(this).find('.levl').attr('id','level_'+i);
            $(this).find('.quecount').attr('name','count_'+i);
            $(this).find('.quecount').attr('id','count_'+i);
            $(this).find('.quecategory').attr('name','category_'+i);
            $(this).find('.quecategory').attr('id','category_'+i);
            i++;
        });
    }
    </script>