<?php
$this->inlineScript()->appendFile($this->basePath() . '/js/koolguru/package/package.js');
$form = $this->form;
$form->setAttribute('action', $this->url('quiz', array('action' => 'edit', 'id' => $id, 'page' => $page)));
$form->setAttribute('class', 'detect_changes');
$form->prepare();
echo $this->form()->openTag($form);
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
?>
<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
            <?php
            $title = 'Edit Quiz';
            ?>
            <a class="back-icon" href="<?php echo $this->url('quiz', array('action' => 'index')); ?>"></a>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>
                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
                <?php //echo $this->content; ?>

            </h1>
        </div>
        <div class="sub-header-actions"></div>
    </div>
</section>

<div class="container">
    <div class="forms" id="add-trainee-form">
        <?php
        $errorflashMessage = $this->flashMessenger()->getCurrentErrorMessages();
        $successflashMessage = $this->flashMessenger()->getCurrentSuccessMessages();
        if (empty($errorflashMessage) && !empty($successflashMessage)) {
            ?>
            <div id="global-success-msg-page" class="global-page-success">
                <?php
                foreach ($successflashMessage as $succMsg) {
                    echo $errMsg;
                }
                ?>

            </div>
            <?php
        } else {
            if (!empty($errorflashMessage)) {
                ?>
                <div id="global-error-msg-page"   class="global-page-error"><?php
                    foreach ($errorflashMessage as $errMsg) {
                        echo $errMsg;
                    }
                    ?></div>
                <?php
            }
        }
        ?>
<!--        <div class="upper-submit">
            <?php
            echo $this->formSubmit($form->get('submit'));
            ?>
        </div>-->
        <div id="step1">
            <section id="basic_details">
                <input type="hidden" id="rowcount" name="rowcount" value="1">
                <?php
                echo $this->formHidden($form->get('id'));
                ?>

                <ul>
                    <li class="form-row">                    
                        <label class='label'>Title: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('title')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Subject: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('subject_id')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Chapter: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('chapter_id')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Code: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('code')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>DESCRIPTION: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('description')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Passing Percentage: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('pass_percentage')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>Start Time: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('start_time')); ?>
                    </li>
                    <li class="form-row">                    
                        <label class='label'>End Time: <span class='required'>*</span></label>
                        <?php echo $this->formElement($form->get('end_time')); ?>
                    </li>                    
                    <li class="form-row">                    
                        <label class='label'>IS ACTIVE: </label>
                        <?php echo $this->formElement($form->get('status')); ?>
                    </li>
                    
                    <li class="form-row">
                        <?php $i=1;foreach($quizlevel as $data){?>
                        <div class="quiz-level" row="1">
                            <div class="pull-left width-100">
                                <div>Question Level</div> 
                                <select class="levl" name="level_<?php echo $i;?>" id="level_<?php echo $i;?>">
                                    <option value="">Select</option>
                                    <?php foreach($levelList as $k=>$v){?>
                                        <?php if($k == $data['level_id']){?>
                                            <option selected value="<?php echo $k;?>"><?php echo $v;?></option>
                                        <?php }else{ ?>
                                            <option value="<?php echo $k;?>"><?php echo $v;?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="pull-left width-100 quiz-left">
                                <div>Question Count</div>
                                    <input type="text" id="count_<?php echo $i;?>" class="quecount text-height" name="count_<?php echo $i;?>" value="<?php echo $data['ques_nos']?>">
                            </div>
                            <div class="pull-left width-100 quiz-left">
                                <div>Category</div>
                                <select class="quecategory" name="category_<?php echo $i;?>" id="category_<?php echo $i;?>">
                                    <option value="">Select</option>
                                    <?php foreach($que_category as $k=>$v){?>                                        
                                        <?php if($k == $data['category_id']){?>
                                            <option selected value="<?php echo $k;?>"><?php echo $v;?></option>
                                        <?php }else{ ?>
                                            <option value="<?php echo $k;?>"><?php echo $v;?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="pull-left quiz-left"> 
                                <div class="add-icon" id="addrow"></div>
                            </div>
                            <div class="pull-left quiz-left">
                                <div class="delete-icon" id="delrow"></div>                                    
                            </div>
                        </div>
                        <?php if(count($quizlevel) != $i){?>
                        </br></br></br></br>
                        <?php } ?>
                        <?php $i++;} ?>
                    </li>
                </ul>
            </section>
        </div>
        <div id="step2">
            <section id="basic_details">
                <?php
                echo "<h2 class='h2'>Add Courses</h2>";
                ?>
                <ul>
                    <li class="form-row">                    
                        <label class='label'>SELECT COURSE: </label>
                        <?php echo $this->formElement($form->get('id')); ?>
                    </li>
                    <li class="form-row">
                        <a href="javascript:void(0)" class="green-btn big-btn" id="add_option">Add Course</a>
                    </li>
                </ul>
            </section>
            <table border="1" class="table center-listing" id="course_table">
                <thead>
                    <tr>
                        <th class="fname"><input type='hidden' id='action' value='add'><?php echo $this->escapeHtml('COURSE NAME'); ?></th>
                        <th class="actions"><?php echo $this->escapeHtml('ACTION'); ?></th>
                    </tr>
                </thead>
                
            </table>
        </div>        
        <?php
        echo $this->formHidden($form->get('created_at'));
        echo $this->formHidden($form->get('created_by'));
        echo $this->formHidden($form->get('updated_at'));
        echo $this->formHidden($form->get('updated_by'));
        ?>

        <div id="form-footer">
            <?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.add-icon').click(function(){
            addnewrow(this)
        });
        
        $('.delete-icon').click(function(){
            deleterow(this);
        });
    
        $('#subject_id').change(function(){
            getChapter($(this).val(),'');
        });
        getChapter($('#subject_id').val(),'<?php echo $quiz->chapter_id;?>');
    });
    
    function getChapter(subject,chapter_id){            
        var url = '<?php echo $this->basePath() . '/quiz/getchapter?subject='; ?>' + subject;
        $.ajax({url: url, success: function (result) {
                var html = '<option value="">Select</option>';
                $.each(JSON.parse(result), function(idx, obj) {
                    if(chapter_id == ''){                        
                        html += "<option value='"+obj.chapter_id+"'>"+obj.chaptertitle+"</option>";
                    }else{
                        if(obj.chapter_id == chapter_id){
                            html += "<option selected value='"+obj.chapter_id+"'>"+obj.chaptertitle+"</option>";
                        }else{
                            html += "<option value='"+obj.chapter_id+"'>"+obj.chaptertitle+"</option>";
                        }
                    }
                });
                $('#chapter_id').html(html);
        }});
    }
    
    function addnewrow(obj){
        var clone = $(obj).parent().parent().clone();
        $(obj).parent().parent().parent().append('</br></br></br></br>');
        $(obj).parent().parent().parent().append(clone);
        manageRows();
    }
    
    function deleterow(obj){  
        if($('.quiz-level').length > 1){
            $(obj).parent().parent().remove();
            manageRows();
        }else{
            alert('You can not delete all');
            return false;
        }
    }
    
    function bindclick(obj){        
        $(obj).find('.add-icon').click(function(){
            addnewrow(this);
        });
        $(obj).find('.delete-icon').click(function(){
            deleterow(this);
        });
    }
    
    function manageRows(){
        var i = 1;
        $('.quiz-level').each(function(){
            $(this).attr('row',i);
            $(this).find('.levl').attr('name','level_'+i);
            $(this).find('.levl').attr('id','level_'+i);
            $(this).find('.quecount').attr('name','count_'+i);
            $(this).find('.quecount').attr('id','count_'+i);
            $(this).find('.quecategory').attr('name','category_'+i);
            $(this).find('.quecategory').attr('id','category_'+i);
            bindclick(this);
            $('#rowcount').val(i);
            i++;
        });
        
    }
    </script>