<?php
echo $this->doctype();
if (isset($_SESSION['User']['userId'])):
    $roleCode = $_SESSION['User']['userId'];
endif;
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('KoolGuru') ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/animate.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800,900')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300:700')
                ->prependStylesheet($this->basePath() . '/css/nav.css')
                ->prependStylesheet($this->basePath() . '/css/slider.css')
                ->prependStylesheet($this->basePath() . '/js/fancybox/jquery.fancybox.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/video.js')
                ->prependFile($this->basePath() . '/js/wow.min.js')
                ->prependFile($this->basePath() . '/js/fancybox/jquery.fancybox.pack.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/jquery.openCarousel.js')
                ->prependFile($this->basePath() . '/js/modernizr.custom.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')

        ;
        ?>

        <link href="http://vjs.zencdn.net/5.0.2/video-js.css" rel="stylesheet">

        <script>
            new WOW().init();
        </script>

        <script>
            $(function () {
                var button = $('#loginButton');
                var box = $('#loginBox');
                var form = $('#loginForm');
                button.removeAttr('href');
                button.mouseup(function (login) {
                    box.toggle();
                    button.toggleClass('active');
                });
                form.mouseup(function () {
                    return false;
                });
                $(this).mouseup(function (login) {
                    if (!($(login.target).parent('#loginButton').length > 0)) {
                        button.removeClass('active');
                        box.hide();
                    }
                });
            });
            
            var app = {};
        </script>
    </head>
    <body>        
        <!-- Header -->
        <div class="header">    
            <div class="header_top">
                <div class="container">

                    <div class="headertop_nav">
                            <ul>
                                <li>Call Us </li>
                                <li> :(000) 123-456 </li> 
                                <li> Email us : </li> 
                                <li>info@koolguru.co.in</li> 
                            </ul>
                        </div>
                </div>
            </div>
            <div class="header_bottom">
                <div class="container">	 			
                    <div class="logo">
                        <h1><a href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath() . '/img/logo.png' ?>"><span></span></a></h1>
                    </div>	
                    <?php if (isset($roleCode)) { ?>
                        <div class="navigation">	
                            <div>
                                <label class="mobile_menu" for="mobile_menu">
                                    <span>Menu</span>
                                </label>
                                <input id="mobile_menu" type="checkbox">
                                <ul class="nav">
                                    <li><a href="<?php echo $this->url('home'); ?>">Home</a></li>
                                    <li></li>
                                    <li><a href="<?php echo $this->url('student'); ?>">Registration</a></li>  
                                    <li></li>
                                    <li><a href="about.html">About</a></li>                                    
                                    <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'contactus')); ?>">Contact</a></li>
                                    <div class="clearfix"></div>
                                </ul>
                            </div>			
                        </div>

                        <div class="header-top-right">
                            <div class="login_box">
                                <div id="loginContainer">
                                    <a href="<?php echo $this->url('logout') ?>" class="logout-btn">Logout</a>
                                </div>
                            </div> 
                        </div>
                    <?php } else { ?>
                        <div class="header-top-right">
                            <div class="login_box">
                                <div id="loginContainer">
                                    <a href="<?php echo $this->url('login') ?>" class="logout-btn">Login</a>
                                </div>
                            </div> 
                        </div>
                    <?php } ?>
                </div>
            </div>	

        </div>
    </div>
    <!-- Ends Header -->


    <!-- Move message Divs to each pages individually as per design required -->
        <!--<div class="success"><?php //echo $this->flashMessage();             ?></div>
        <div class="error"></div>-->            
        <div class="container">

            <section class="error-container">
                <p class="error-type error-icon"></p>
                <div class="forbidden-content">
                    <p class="error-content">Access Denied!</p>
                    <p class="error-links">You are not authorized to view this page.</p>
                </div>
            </section>



        </div>


    <div class="footer">
        <div class="container">   	 
            <div class="footer_top">
                <div class="row">
                    <div class="col-md-4 footer_grid">
                        <h4>Receive our Newsletter</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    </div>
                    <div class="col-md-4 footer_grid">
                        <h4>Info</h4>
                        <div class="footer-list">
                            <ul>
                                <li class="list_top">                                    
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'locateus')); ?>">Locate Us</a>
                                </li>
                                <li class="list_top">                                    
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>">About Us</a>
                                </li>
                                <li class="list_top">
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'vision')); ?>">Vision</a>
                                </li>
                                <li class="list_top">
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'mission')); ?>">Mission</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 footer_grid">
                        <h4>Our Address</h4>
                        <div class="company_address">
                            <p>79, Sector E pocket 2
                            <p>Vasant Kunj</p>
                            <p>New Delhi 110070</p>                            
                            <p>India</p>
                            <p>Phone:(00) 222 666 444</p>                            
                            <p>Email: <span><a href="mailto:info@koolguru.co.in">info@koolguru.co.in</a></span></p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="footer_bottom">
                <div class="copy_right">
                    <p>&copy; 2015 All Rights Reseverd | Version: Beta 1.0</p>
                </div>
                <div class="footer_nav">
                    <ul>
                        <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
                        <li><a href="#">Terms of use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'contactus')); ?>">Contact</a></li>
                    </ul>
                </div>
                <div class="clearfix"></div>
                <script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=73064553"></script>
            </div>
        </div>
    </div>
    <?php echo $this->inlineScript() ?>
</body>
</html>

