<?php
$title = 'Change Password';
$this->headTitle($title);
$errMsg = $this->errRecVar;
?>
<section class="sub-header">
    <div class="container">

        <div class="sub-header-title">
            <a class="back-icon" title="Return to Home" href="<?php echo $this->url('application', array('action' => 'index')); ?>"></a>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>
                <div class="sub-header-breadcrumb">
                    <a href="<?php echo $this->url('home') ?>"><span class="home"></span></a>    
                    <span class="breadcrumb-arrow"> > </span>
                    <span>Change Password</span>
                </div>
                <?php
                /* Adding Breadcrumb */
//                echo $this->navigation('navigation')
//                        ->breadcrumbs()
//                        ->setMinDepth(0)
//                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
            </h1></div>
        <div class="sub-header-actions"></div>
    </div>
</section>
<div class="container">
    <?php $flashMessage = $this->flashMessenger()->getMessages(); ?>
    <div id="global-success-msg" class="success global-success"></div>
    <div id="global-error-msg" class="error global-error"><?php echo $this->flashMessage(); ?></div>


    <div class="forms" id="add-sector-form">
        <!--<h1><?php /* ?><?php echo $this->escapeHtml($title); ?><?php */ ?></h1>-->
        <?php
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <ul>
            <li class = "form-row">
                <label class="label" for="OldPassword">Old Password</label>
                <?php echo $this->formElement($form->get('oldpassword')); ?>
            </li>
            <li class = "form-row">
                <label class="label" for="NewPassword">New Password</label>
                <?php echo $this->formElement($form->get('password')); ?>
            </li>
            <li class = "form-row">
                <label class="label" for="Retypepassword">Retype-password</label>
                <?php echo $this->formElement($form->get('repassword')); ?>	
            </li>
        </ul>
        <div id="form-footer">
            <?php echo $this->formElement($form->get('submit')); ?>   
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<?php
//echo $this->formElementerrors($form->get('password')); 
$messages = $form->getMessages();
$validationErrors = array();
foreach (array_keys($messages) as $name) {
    foreach ($messages[$name] as $k => $v) {
        //$v = ucfirst($name).' field - '.$v;
        array_push($validationErrors, $v);
    }
}
?>
<p></p>
<?php if (count($validationErrors) > 0) { ?>
    <div class="reg23_error" style="display:block;">
        <ul style="padding:0;margin:0;margin-left:15px;">
            <?php
            foreach ($validationErrors as $key => $values) {
                echo "<li>" . $values . "</li>";
            }
            ?>
        </ul>
    </div>
<?php } ?>

<script type="text/javascript">
    //validation for no 
    $(document).ready(function() {
        $('#resetpassword').validate({
            rules: {
                oldpassword: {
                    required: true,
                },
                password: {
                    required: true,
                    minlength: 8,
                    maxlength: 20
                },
                repassword: {
                    required: true,
                    minlength: 8,
                    maxlength: 20,
                    equalTo: "#password"
                },
            },
            messages: {
                oldpassword: {
                    required: "Please enter old password.",
                },
                password: {
                    required: "Please enter new password.",
                    minlength: "Minimum 8 characters required",
                    maxlength: "Maximum 20 characters required"
                },
                repassword: {
                    required: "Please retype new password.",
                    minlength: "Minimum 8 characters required",
                    maxlength: "Maximum 20 characters required"
                },
            }
        });

        jQuery.extend(jQuery.validator.messages, {
            //required: "This field is required.",
            //remote: "Please fix this field.",
            // email: "Please enter a valid email address.",
            //  url: "Please enter a valid URL.",
            // date: "Please enter a valid date.",
            //  dateISO: "Please enter a valid date (ISO).",
            //  number: "Please enter a valid number.",
            //  digits: "Please enter only digits.",
            //   creditcard: "Please enter a valid credit card number.",
            equalTo: "New Password and Retype Password should match.",
            //   accept: "Please enter a value with a valid extension.",
            //   maxlength: jQuery.validator.format("Please enter no more than {0} characters."),
            //   minlength: jQuery.validator.format("Please enter at least {0} characters."),
            //    rangelength: jQuery.validator.format("Please enter a value between {0} and {1} characters long."),
            //    range: jQuery.validator.format("Please enter a value between {0} and {1}."),
            //    max: jQuery.validator.format("Please enter a value less than or equal to {0}."),
            //    min: jQuery.validator.format("Please enter a value greater than or equal to {0}.")
        });



    });
</script> 