<?php
if (isset($this->successMessage)) {
    echo $this->successMessage;
}

$flashMessage = $this->flashMessenger()->getMessages();

if (count($flashMessage)) :
    ?>
    <div>
        <ul id="global-error-msg-page" class="global-page-error">
            <?php
            foreach ($flashMessage as $msg) :
                foreach ($msg as $type => $message) :
                    ?>
                    <li><span class="<?php echo $type; ?>"><?php echo $message; ?></span></li>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if (isset($this->messages)) : ?>
        <ul>
            <?php foreach ($this->messages as $type => $msg) : ?>
                <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>

<?php
$form = $this->form;
$form->prepare();
$title = 'Reset Password';
$this->headTitle($title);
$errMsg = $this->errRecVar;
?>

<script>
    function showMSg(textMSg) {
        if (textMSg != '') {
            $('#recoverlinkForm').hide();
            $('.panel-default').append('<div>Activation link is either expired/used</div>');
            $('#messageErrExam').text(textMSg);
            $("#messageErrExam").fadeIn("slow").fadeOut(100 * 15);
<?php if ($errMsg == 2) { ?>
                window.location.href = "<?php echo $this->basePath(); ?>";
<?php } ?>
        }
    }

</script>


<p></p>


<div class="full_height">

    <div class="login_base">
        <!--<div class="logo"></div>-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <div class="panel-body register-container" id="recoverlinkForm">
                <form class="rl-form" name="rl-form" id="rl-form" method="post">
                    <?php echo $this->formlabel($form->get('password')); ?>
                    <p>
                        <?php echo $this->formElement($form->get('password')); ?>
                        <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('email')); ?></span>
                    </p>
                    <?php echo $this->formlabel($form->get('repassword')); ?>
                    <p>
                        <?php echo $this->formElement($form->get('repassword')); ?>
                        <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('email')); ?></span>
                    </p>

                    <div class="row">
                        <div class="col-xs-5"> <?php
                            echo $this->formElement($form->get('submit'));
                            ?></div><div class="col-xs-7 text-right"><a class="recover_link grey-anchor" href="<?php echo $this->url('login', array('action' => 'index'));
                            ?>">Click here to Login again</a></div></p>
                        <p></p>

                    </div>		
                </form>
            </div>
        </div>
    </div></div>

<?php
//echo $this->formElementerrors($form->get('password')); 
$messages = $form->getMessages();
$validationErrors = array();
foreach (array_keys($messages) as $name) {
    foreach ($messages[$name] as $k => $v) {
        //$v = ucfirst($name).' field - '.$v;
        array_push($validationErrors, $v);
    }
}
?>
<?php if (count($validationErrors) > 0 || $errMsg == 1 || $errMsg == 2) { ?>
    <div class="reg23_error" style="display:block;">
        <ul>
            <?php
            foreach ($validationErrors as $key => $values) {
                echo "<li>" . $values . "</li>";
            }
            ?>
        </ul>
        <?php
        if ($errMsg == 1) {
            $textMsg = 'Please create a new link to change your password. The Previous link has expired.';
            echo '<script>showMSg("' . $textMsg . '")</script>';
        }
        if ($errMsg == 2) {
            $textMsg = 'Password has been changed successfully.';
            echo '<script>showMSg("' . $textMsg . '")</script>';
        }
        ?>
    </div>
<?php } ?>
<script type="text/javascript">
    $(document).ready(function() {
        $("#rl-form").validate({
            rules: {
                password: {
                    required: true,
                    minlength: 8,
                    maxlength: 12
                },
                repassword: {
                    required: true,
                    minlength: 8,
                    maxlength: 12,
                    equalTo: "#password"
                }
            },
            messages: {
                password: {
                    required: "Password is required.",
                    minlength: "Minimum 8 characters required",
                    maxlength: "Maximum 12 characters required"
                },
                repassword: {
                    required: "Confirm password is also required.",
                    minlength: "Minimum 8 characters required",
                    maxlength: "Maximum 12 characters required"
                },
            },
        });
    });
</script>

