<?php
$form = $this->form;
$form->setAttribute('action', $this->url('level', array('action' => 'edit','id'=>$id,'page'=>$page)));
$form->setAttribute('class', 'detect_changes');
$form->prepare();
echo $this->form()->openTag($form);
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
?>
<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
            <?php
            $title = 'Create Level';
            $this->headTitle($title);
            ?>
            <a class="back-icon" href="<?php echo $this->url('level', array('action' => 'index')); ?>"></a>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>
                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
                <?php //echo $this->content; ?>

            </h1>
        </div>
        <div class="sub-header-actions"></div>
    </div>
</section>

<div class="container">
    <div class="forms" id="add-trainee-form">
        <?php if (empty($errorflashMessage)) { ?>
            <div id="global-success-msg-page" class="global-page-success">
                <?php
                $successflashMessage = $this->flashMessenger()->getCurrentMessagesFromNamespace('success');
                foreach ($successflashMessage as $succMsg) {
                    echo $errMsg;
                }
                ?>

            </div>
        <?php } else { ?>
            <div id="global-error-msg-page"   class="global-page-error"><?php
                foreach ($errorflashMessage as $errMsg) {
                    echo $errMsg;
                }
                ?></div>
        <?php } ?>
        <section id="basic_details">
            <?php
            echo "<h2 class='h2'>Basic Details</h2>";
            echo $this->formHidden($form->get('id'));
            ?>
            <ul>
                <li class="form-row">                    
                    <label class='label'>LEVEL NAME: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('name')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>DESCRIPTION: </label>
                    <?php echo $this->formElement($form->get('description')); ?>
                </li>
        </section>

        <?php
        echo $this->formHidden($form->get('created_date'));
        echo $this->formHidden($form->get('created_by'));
        echo $this->formHidden($form->get('updated_date'));
        echo $this->formHidden($form->get('updated_by'));
        ?>
        <div id="form-footer">
            <?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div> <!--add_trainee_form div close-->
</div>