<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
                'center', array(
            'action' => 'edit',
            'id' => $this->id,
            'page' => $this->page
                )
));
$form->setAttribute('class', 'detect_changes');
$form->prepare();
echo $this->form()->openTag($form);
?>
<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
            <?php
            $this->headScript()->appendFile($this->basePath() . '/js/hijricalendar/jquery.plugin.js');
            $this->headScript()->appendFile($this->basePath() . '/js/radio-checkbox.js');
            $this->headScript()->appendFile($this->basePath() . '/js/sss_js/center.js');
            $title = 'Edit Center';
            $this->headTitle($title);
            ?>
            <a class="back-icon" href="<?php echo $this->url('center', array('action' => 'index')); ?>"></a>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>
                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
                <?php //echo $this->content; ?>

            </h1>
        </div>
        <div class="sub-header-right"></div>
    </div>
</section>

<div class="container">
    <div class="forms" id="add-trainee-form">
        <div id="global-success-msg" class="success global-success"></div>
        <div id="global-error-msg" class="error global-error"><?php echo $this->flashMessage(); ?></div>
        <section id="basic_details">
            <?php
            echo "<h2 class='h2'>Basic Details</h2>";
            echo $this->formHidden($form->get('id'));
            ?>
            <ul>
                <li class="form-row">                    
                    <label class='label'>CENTER NAME: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('name')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>CENTER SHORT NAME: </label>
                    <?php echo $this->formElement($form->get('short_name')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>GROUP NAME: </label>
                    <?php echo $this->formElement($form->get('group_name')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>CENTER TYPE: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('center_type')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>GENDER OF CENTER: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('gender')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>UPLOAD CENTER LOGO: </label>
                    <?php
                    echo"<div class='clearfix pRelative'>";
                    echo"<input id='uploadFile' class='input pageUploadFile' placeholder='Choose File' disabled='disabled' value=''/>";
                    echo"<div class='fileUpload'>";
                    echo"<span class='green-btn big-btn page-upload-btn'>Browse</span>";
                    echo $this->formElement($form->get('center_logo'));
                    echo"</div>";
                    echo"</div>";
                    ?>
                    <span class="upload-instruction">MAXIMUM SIZE  1MB</span>
                    <?php if ($center_detail->center_logo != '') { ?>
                    <li class="form-row">
                        <img src="<?php echo $this->basePath(); ?>/uploads/center_logo/resized_logo/<?php echo $center_detail->center_logo; ?>">
                    </li>    
                <?php } ?>
                </li>
            </ul>
        </section> <!--basic_details section close-->
        <div class="form-divider marginTB20"></div>
        <section id="contact_details">
            <?php
            echo "<h2 class='h2'>Contact Details</h2>";
            ?>
            <ul>
                <li class="form-row">                    
                    <label class='label'>PRIMARY EMAIL ID: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('email')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>SECONDARY EMAIL ID: </label>
                    <?php echo $this->formElement($form->get('secondary_email')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>CENTER ADDRESS: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('address_1')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>REGION: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('state')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>CITY: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('city')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>AREA PINCODE: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('zip')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>PHONE: <span class='required'>*</span></label>
                    <?php echo $this->formElement($form->get('phone')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>FAX: </label>
                    <?php echo $this->formElement($form->get('fax')); ?>
                </li>
                <li class="form-row">                    
                    <label class='label'>NAME OF CONTACT PERSON: <span class='required'>*</span> </label>
                    <span class="contact-person-field">
                        <?php
                        echo $this->formElement($form->get('poc_fname'));
                        ?>
                    </span>
                    <span class="contact-person-field">
                        <?php
                        echo $this->formElement($form->get('poc_lname'));
                        ?>
                    </span>
                </li>
                <li class="form-row">                    
                    <label class='label'>WEBSITE ADDRESS: </label>
                    <?php echo $this->formElement($form->get('website')); ?>
                </li>
            </ul>
        </section>

        <?php
        //echo $this->formHidden($form->get('created_date'));
        // echo $this->formHidden($form->get('created_by'));
        echo $this->formHidden($form->get('updated_date'));
        echo $this->formHidden($form->get('updated_by'));
        ?>
        <div id="form-footer">
            <?php
            if ($center_detail->status == 'Draft') {
                echo $this->formSubmit($form->get('draftsubmit'));
            }
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div> <!--add_trainee_form div close-->
</div>
<script>
    $('#center_logo').change(function() {
        var _val = this.value;
        if (_val != '') {
            $("#uploadFile").val(_val);
            var fileSize = this.files[0].size / 1000;
            var ext = _val.split('.').pop().toLowerCase();
            if ($.inArray(ext, ['gif', 'png', 'jpg', 'jpeg']) == -1) {
                $('#uploadFile').val("");
                $('#center_logo').val("");
                alert('Sorry, the file you are trying to upload is not as per the prescribed format. Please upload the files in the format jpeg,gif,png');
            } else if (fileSize > 1000) {
                $('#uploadFile').val("");
                $('#center_logo').val("");
                alert('Please upload the file size max of 1 MB.');
            }
        }

    });
</script>