<script type="text/javascript">
    $(document).ready(function () {
        $('#parent_role').select2('readonly', true);
        $('#role_name').attr('readonly', true);
        $('#role_name').addClass('input-disabled');
    });
</script>
<section class="sub-header">
    <div class="container">

        <div class="sub-header-title">
            <?php
            $title = 'Edit Role';
            //$this->headScript()->appendFile($this->basePath() . '/js/radio-checkbox.js');
//            echo "<pre>";
//            print_r($this->resourceName);
//            die;
            ?>
            <a class="back-icon" href="<?php echo $this->url('userrole', array('action' => 'index')); ?>"></a>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>
                <!-- <div class="sub-header-breadcrumb">
                    <a href="<?php echo $this->url('home') ?>"><span class="home"></span></a>    
                    <span class="breadcrumb-arrow"> > </span>
                    <a href="#">MANAGE User</a>
                    <span class="breadcrumb-arrow"> > </span>
                    <span>Add User</span>
                  </div>-->
                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
            </h1>
        </div>
        <div class="sub-header-actions"></div>
    </div>
</section>

<div class="container">
    <div class="forms" id="add-user-form">
        <div id="global-success-msg" class="success global-success"></div>
        <div id="global-error-msg"   class="error global-error"><?php echo $this->flashMessage(); ?></div>

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('userrole', array('action' => 'edit', 'id' => $this->id)));
        $form->setAttribute('class', 'detect_changes');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <section id="basic_details">
            <?php echo "<h2 class='h2'></h2>"; ?>
            <ul>
                <li class="form-row">
                    <?php
                    echo"<label class='label'>Role Name:<span class='required'>*</span></label>";
                    echo $this->formElement($form->get('role_name'));
                    ?>
                </li>
                <li class="form-row">
                    <?php
                    echo"<label class='label'>Role Code:<span class='required'>*</span></label>";
                    echo $this->formElement($form->get('role_code'));
                    ?>
                </li>
                <li class="form-row">
                    <?php
                    echo"<label class='label'>Parent Role:<span class='required'>*</span></label>";
                    echo $this->formElement($form->get('parent_role'));
                    ?>
                </li>
            </ul>
            <div id="edit_permission">
                <ul>
                    <li class="form-row" id='edit_permission_label'>
                        <?php
                        echo"<label class='label'>ACCESS PERMISSIONS:<span class='required'>*</span></label>";
                        ?>
                    </li>

                </ul>

                <?php if (!empty($this->resourceName)) { ?>
                    <table id='editPermissionTable' class='table prerequsite-table permission-table'>
                        <thead>
                            <tr>
                                <th>MODULE</th>
                                <th>READ ONLY</th>
                                <th>FULL ACCESS</th>
                                <th>DISABLE</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->resourceName as $res) :
                                $resourceArr = explode('*', $res);
                                ?>
                                <tr>                                         
                                    <td><input type='hidden' name='<?php echo $resourceArr[1]; ?>' value='<?php echo $resourceArr[1]; ?>'><?php
                                        if ($this->roleCode != 'sa' && $resourceArr[0] == 'User') {
                                            echo "Profile";
                                        } else {
                                            echo $resourceArr[0];
                                        }
                                        ?></td>
                                    <?php if (in_array($resourceArr[1], $this->readAccess)) { ?>
                                        <td class="rbtnCount"><input class="css-radio" type="radio" name="permissionRadio_<?php echo $resourceArr[1]; ?>" id="readOnly_<?php echo $resourceArr[1]; ?>" value="readOnly_<?php echo $resourceArr[1]; ?>" checked="checked"><label class="css-radio-label" for="readOnly_<?php echo $resourceArr[1]; ?>"></label></td>
                                    <?php } else { ?>
                                        <td class="rbtnCount"><input class="css-radio" type="radio" name="permissionRadio_<?php echo $resourceArr[1]; ?>" id="readOnly_<?php echo $resourceArr[1]; ?>" value="readOnly_<?php echo $resourceArr[1]; ?>"><label class="css-radio-label" for="readOnly_<?php echo $resourceArr[1]; ?>"></label></td>
                                    <?php } ?>
                                    <?php if (in_array($resourceArr[1], $this->fullAccess)) { ?>
                                        <td class="rbtnCount"><input class="css-radio" type="radio" name="permissionRadio_<?php echo $resourceArr[1]; ?>" id="fullAccess_<?php echo $resourceArr[1]; ?>" value="fullAccess_<?php echo $resourceArr[1]; ?>" checked="checked"><label class="css-radio-label" for="fullAccess_<?php echo $resourceArr[1]; ?>"></label></td>
                                    <?php } else if (in_array($resourceArr[1], $this->onlyReadResource)) { ?>
                                        <td class="rbtnCount"><input class="css-radio" type="radio" disabled="disabled" name="permissionRadio_<?php echo $resourceArr[1]; ?>" id="fullAccess_<?php echo $resourceArr[1]; ?>" value="fullAccess_<?php echo $resourceArr[1]; ?>"><label class="css-radio-label" onmouseover="showTooltip('fullAccess_<?php echo $resourceArr[1]; ?>')" onmouseout="hideTooltip('fullAccess_<?php echo $resourceArr[1]; ?>')" for="fullAccess_<?php echo $resourceArr[1]; ?> ">
                                                <span class="edit-help" id="edit-tooltip-details-<?php echo $resourceArr[1]; ?>">Parent role does not have full access for <?php echo $resourceArr[0]; ?> module.</span>
                                            </label></td>
                                    <?php } else { ?>
                                        <td class="rbtnCount"><input class="css-radio" type="radio" name="permissionRadio_<?php echo $resourceArr[1]; ?>" id="fullAccess_<?php echo $resourceArr[1]; ?>" value="fullAccess_<?php echo $resourceArr[1]; ?>"><label class="css-radio-label" for="fullAccess_<?php echo $resourceArr[1]; ?>"></label></td>
                                    <?php } ?>
                                    <?php if (in_array($resourceArr[1], $this->noAccess)) { ?>
                                        <td class="rbtnCount"><input class="css-radio" type="radio" name="permissionRadio_<?php echo $resourceArr[1]; ?>" id="disable_<?php echo $resourceArr[1]; ?>" value="disable_<?php echo $resourceArr[1]; ?>" checked="checked"><label class="css-radio-label" for="disable_<?php echo $resourceArr[1]; ?>"></label></td>
                                    <?php } else { ?>
                                        <td class="rbtnCount"><input class="css-radio" type="radio" name="permissionRadio_<?php echo $resourceArr[1]; ?>" id="disable_<?php echo $resourceArr[1]; ?>" value="disable_<?php echo $resourceArr[1]; ?>"><label class="css-radio-label" for="disable_<?php echo $resourceArr[1]; ?>"></label></td>
                                    <?php } ?>

                                </tr>
                                <?php
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                    <?php
                } else {
                    ?>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>MODULE</th>
                                <th>READ ONLY</th>
                                <th>FULL ACCESS</th>
                                <th>DISABLE</th>
                            </tr>
                        </thead>
                        <tbody><tr><td colspan="4"><div class="no-records"><span class="info-icon"></span>No Permission Found !</div></td></tr>
                        </tbody>
                    </table>
                <?php }
                ?>
            </div>
        </section>

        <section id="contact_details">
            <div class="form-footer"><?php
                echo $this->formInput($form->get('submit'));
                echo $this->form()->closeTag();
                ?> </div>
        </section>
    </div>
</div>


<!--Temporary script for edit tooltips-->
<script>
    var editHelp = $("#edit-tooltip");
    var editHelpDetails = $("#edit-tooltip-details");
    function showTooltip(id) {
        var idArr = id.split('_');
        $("#edit-tooltip-details-" + idArr[1]).css({"display": "block"});
    }
    function hideTooltip(id) {
        var idArr = id.split('_');
        $("#edit-tooltip-details-" + idArr[1]).css({"display": "none"});
    }

</script>