<?php
//If this is not ajax request load javascript
//$this->inlineScript()->appendFile('js/sss_js/unit.js');
$title = 'Manage Roles';
$this->headTitle($title);
$default_order = 'ASC';
$url_order = $this->order == 'ASC' ? 'DESC' : 'ASC';
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
$query = '';
if (isset($data['search_box'])) {
    $query .= '&search_box=' . $data['search_box'];
}

if (!$this->isAjax) {
    ?>
    <section class="sub-header">
        <div class="container">
            <div class="sub-header-title">
                <span class="manage-qualification-icon"></span>
                <h1 class="h1"><?php echo $this->escapeHtml($title); ?>   
                    <?php
                    /* Adding Breadcrumb */
                    echo $this->navigation('navigation')
                            ->breadcrumbs()
                            ->setMinDepth(0)
                            ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                    ?>
                </h1>
            </div>
            <div class="sub-header-actions">
                <a class="big-btn green-btn" href="<?php echo $this->url('userrole', array('action' => 'add')); ?>">CREATE</a>
            </div>
        </div>
    </section>

    <div class="container">
        <?php if (empty($errorflashMessage)) { ?>
            <div id="global-success-msg" class="success global-success"><?php echo $this->flashMessage(); ?></div>
        <?php } ?>
        <div id="global-error-msg"   class="error global-error"></div>
        <?php
        $search_form = $this->form;
        $search_form->setAttribute('action', $this->url('userrole', array('action' => 'index')));
        $search_form->prepare();
        echo $this->form()->openTag($search_form);
        ?>
        <div class="action-table">
            <div class="filter-table">
                <?php
                echo $this->formRow($search_form->get('list_count'));
                echo $this->formRow($search_form->get('order_by'));
                echo $this->formRow($search_form->get('order'));
                ?>
            </div>
            <div class="search-table">
                <span class="search-holder">
                    <?php
                    echo $this->formRow($search_form->get('search_box'));
                    echo $this->formRow($search_form->get('search_box_value'));
                    echo $this->formRow($search_form->get('searchbutton'));
                    echo $this->form()->closeTag();
                    ?>
                </span>
            </div>
        </div>
    <?php } ?>

    <div id="grid-list">
        <?php if ($this->row_count == 0) { ?>
            <table  class="table table-disable">                                
                <thead>
                    <tr>
                        <th>
                            <a href="javascript:void(0);">ID<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th>
                            <a href="javascript:void(0);">ROLE NAME<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th>
                            <a href="javascript:void(0);">ROLE CODE<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>">
                                </i></a>
                        </th>        
                        <th>
                            <a href="javascript:void(0);">TYPE<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>">
                                </i></a>
                        </th>
                        <th class="actions">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="5"><div class="no-records"><span class="info-icon"></span>No records found !</div></td>
                    </tr>
                </tbody>
            </table>

        <?php } else { ?>
            <table  class="table">                                
                <thead>
                    <tr>
                        <th>
                            <a href="javascript:void(0);" onclick="grid.sort('rid', '<?php echo ($this->order_by == 'rid') ? $url_order : $default_order; ?>');">ID<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="role-name">
                            <a href="javascript:void(0);" onclick="grid.sort('role_name', '<?php echo ($this->order_by == 'role_name') ? $url_order : $default_order; ?>');">ROLE NAME<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th>
                            <a href="javascript:void(0);" onclick="grid.sort('role_code', '<?php echo ($this->order_by == 'role_code') ? $url_order : $default_order; ?>');">ROLE CODE<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>        
                        <th>
                            <a href="javascript:void(0);" onclick="grid.sort('parent_role_code', '<?php echo ($this->order_by == 'parent_role_code') ? $url_order : $default_order; ?>');">TYPE<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="actions">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    $i = 0;
                    foreach ($this->paginator as $role) : // <-- change here! 
                        ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($role->rid); ?></td>
                            <td class="role-name"><?php echo $this->escapeHtml($role->role_name); ?></td>
                            <td><?php echo $this->escapeHtml($role->role_code); ?></td>   
                            <td><?php
                                if ($role->parent_role_code == '0') {
                                    echo'System';
                                } else {
                                    echo 'Custom';
                                }
                                ?></td> 
                            <td class="actions">
                                <?php if ($role->parent_role_code != 0) { ?>
                                    <a href="<?php echo $this->url('userrole', array('action' => 'edit', 'id' => $role->rid, 'page' => $this->page)); ?>"> 
                                        <span class="edit-icon" title="edit"></span></a>
                                <?php } else { ?>
                                    <a class="preview-icon" href="<?php echo $this->url('userrole', array('action' => 'view', 'id' => $role->rid, 'page' => $this->page)) ?>"></a>
                                <?php } ?>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>
                </tbody>
            </table> 

            <div class="entries-count pull-right">
                <?php
                if ($this->row_count > ($this->list_count * $this->page)) {
                    ?>
                    <span class="entries">Showing <?php echo 1 + ($this->list_count * ($this->page - 1)); ?> to <?php echo $this->list_count * ($this->page); ?> of <?php echo $this->row_count; ?> entries.</span>
                    <?php
                } else {
                    ?>
                    <span class="entries">Showing <?php echo 1 + ($this->list_count * ($this->page - 1)); ?> to <?php echo $this->row_count; ?> of <?php echo $this->row_count; ?> entries.</span>                
                <?php } ?>
            </div>
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator, 'sliding',
                    // the partial to use to render the control
                    array('partial/paginator.phtml', 'User Role'),
                    // the route to link to when a user clicks a control link
                    array(
                'route' => 'userrole',
                'routeParams' => array('action' => 'index'),
                'jsFunction' => 'grid.list',
                'query' => $this->data,
                'total_row_count' => $this->row_count
                    )
            );
        }
        ?>
    </div>

    <?php
    $this->inlineScript()->appendFile('js/sss_js/searchgrid.js');
    ?>
</div>

