<?php
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
$title = 'Manage Contact Queries';
$this->headTitle($title);
$default_order = 'ASC';
$url_order = $this->order == 'ASC' ? 'DESC' : 'ASC';
$query = '';
if (isset($data['search_box'])) {
    $query .= '&search_box=' . $data['search_box'];
}
if (isset($_SESSION['User']['roleCode'])):
    $roleCode = $_SESSION['User']['roleCode'];
endif;
if (!$this->isAjax) {
    ?>
    <section class="sub-header">
        <div class="container">


            <div class="sub-header-title">
                <span class="manage-center-icon"></span>
                <h1 class="h1"><?php echo $this->escapeHtml($title); ?>   
                    <?php
                    /* Adding Breadcrumb */
                    echo $this->navigation('navigation')
                            ->breadcrumbs()
                            ->setMinDepth(0)
                            ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                    ?>
                </h1>
            </div>
        </div>
    </section>

    <div class="container">

        <?php
        $errorflashMessage = $this->flashMessenger()->getErrorMessages();
        $successflashMessage = $this->flashMessenger()->getCurrentSuccessMessages();
        if (empty($errorflashMessage) && !empty($successflashMessage)) {
            ?>
            <div id="global-success-msg-page" class="global-page-success">
                <?php
                foreach ($successflashMessage as $succMsg) {
                    echo $errMsg;
                }
                ?>

            </div>
        <?php } else { ?>
            <div id="global-error-msg-page"   class="global-page-error"><?php
                foreach ($errorflashMessage as $errMsg) {
                    echo $errMsg;
                }
                ?></div>
        <?php } ?>
        <?php
        $search_form = $this->form;
        $search_form->setAttribute('action', $this->url('admin', array('action' => 'contactquery')));
        $search_form->prepare();
        echo $this->form()->openTag($search_form);
        ?>
        <div class="action-table">
            <div class="filter-table">
                <div class="listing-counts-per-page">
                    <div class="listing-search-dropdown pull-left">
                        <span>
                            <?php
                            echo $this->formRow($search_form->get('list_count'));
                            ?>
                        </span>
                    </div>
                </div>
                <?php
                echo $this->formRow($search_form->get('order_by'));
                echo $this->formRow($search_form->get('order'));
                ?>
            </div>
            <div class="search-table">

                <span class="search-holder">
                    <?php
                    echo $this->formRow($search_form->get('search_box'));
                    echo $this->formRow($search_form->get('search_box_value'));
                    echo $this->formRow($search_form->get('searchbutton'));
                    echo $this->form()->closeTag();
                    ?>
                </span>


            </div>
        </div>
        <?php
    }
    ?>
    <div id="grid-list">

    </div>


</div>
