<div class="container">
    <div class="wpb_wrapper">
        <div class="widget wpo-educator-grid small">
            <div class="widget-content tribe-events-list">
                <div>		
                    <a href="<?php echo $this->url('package', array('action' => 'index')) ?>">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <article class="course course-item"> 
                                <div class="course-image">
                                    <div class="package-box-even">Manage Package</div>                         
                                </div>
                            </article> 
                        </div>
                    </a>
                    <a href="<?php echo $this->url('admin', array('action' => 'course')) ?>">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <article class="course course-item"> 
                                <div class="course-image">
                                    <div class="package-box-odd">Manage Course</div>                                
                                </div>                            	
                            </article> 
                        </div>
                    </a>
                    
                    <a href="<?php echo $this->url('subject', array('action' => 'index')) ?>">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <article class="course course-item"> 
                                <div class="course-image">
                                    <div class="package-box-even">Manage Subject</div>                                
                                </div>                            	
                            </article> 
                        </div>
                    </a>
                    <a href="<?php echo $this->url('chapter', array('action' => 'index')) ?>">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <article class="course course-item"> 
                                <div class="course-image">
                                    <div class="package-box-odd">Manage Chapter</div>                                
                                </div>                            	
                            </article> 
                        </div>    
                    </a>
                </div>
            </div>
            
            
            
            <div class="widget-content tribe-events-list">
                <div>
                    <a href="<?php echo $this->url('level', array('action' => 'index')) ?>">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <article class="course course-item"> 
                                <div class="course-image">
                                    <div class="package-box-even">Manage Question Level</div>                         
                                </div>
                            </article> 
                        </div>
                    </a>
                    <a href="<?php echo $this->url('question', array('action' => 'index')) ?>">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <article class="course course-item"> 
                                <div class="course-image">
                                    <div class="package-box-odd">Manage Question</div>                                
                                </div>                            	
                            </article> 
                        </div>
                    </a>
                    <a href="<?php echo $this->url('question', array('action' => 'index')) ?>">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <article class="course course-item"> 
                                <div class="course-image">
                                    <div class="package-box-even">Manage Career Path</div>                                
                                </div>                            	
                            </article> 
                        </div>
                    </a>
<!--                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <article class="course course-item"> 
                            <div class="course-image">
                                <div class="package-box-odd"></div>                                
                            </div>                            	
                        </article> 
                    </div>                    -->
                </div>
            </div>
        </div>
    </div>
</div>