<?php
echo $this->doctype();
if (isset($_SESSION['User']['roleCode'])):
    $roleCode = $_SESSION['User']['roleCode'];
endif;
$_SESSION['basedomain']['path'] = 'http://localhost/koolguruweb';
?>

<html lang="en">
    <head>
        <script>var app = {};</script>
        <meta charset="utf-8">
        <?php echo $this->headTitle('KOOL GURU - Innovate To Educate') ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <!--<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">-->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/animate.css')
//                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800,900')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300:700')
//                ->prependStylesheet($this->basePath() . '/css/nav.css')
//                ->prependStylesheet($this->basePath() . '/css/slider.css')
                ->prependStylesheet($this->basePath() . '/js/select2/select2.css')
                ->prependStylesheet($this->basePath() . '/js/fancybox/jquery.fancybox.css')
                ->prependStylesheet($this->basePath() . '/js/ajax/libs/jqueryui/1.11.1/themes/smoothness/jquery-ui.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/video.css')
                ->prependStylesheet($this->basePath() . '/css/file.css')
                ->prependStylesheet($this->basePath() . '/css/media-player.css')
                ->prependStylesheet($this->basePath() . '/css_theme/style.css')
                ->prependStylesheet($this->basePath() . '/css_theme/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css_theme/elegant-icons/style.min.css');
        ?>
        <!--        <link href='file.css' rel='stylesheet' />
                <link href='jquery.min.js' rel='stylesheet' />
                <link href='file.js' rel='stylesheet' />
                <script src='media-player.js'></script>
                <link href='media-player.css' rel='stylesheet' />-->
        <!-- Scripts -->
        <?php
        echo $this->headScript()
//                ->prependFile($this->basePath() . '/js/video.js')
                ->prependFile($this->basePath() . '/js/isplayer.js')
                ->prependFile($this->basePath() . '/js/wow.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/select2/select2.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/fancybox/jquery.fancybox.pack.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/koolguru/custom.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/index.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/media-player.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/file.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/jquery.openCarousel.js')
                ->prependFile($this->basePath() . '/js/modernizr.custom.js')
                ->prependFile($this->basePath() . '/js/ajax/libs/jquery.form/3.32/jquery.form.js')
                ->prependFile($this->basePath() . '/js/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js')
                ->prependFile($this->basePath() . '/js/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')



        ;
        ?>



        <script>
            new WOW().init();
        </script>

        <script>
            $(function () {

                var button = $('#loginButton');
                var box = $('#loginBox');
                var form = $('#loginForm');
                button.removeAttr('href');
                button.mouseup(function (login) {
                    box.toggle();
                    button.toggleClass('active');
                });
                form.mouseup(function () {
                    return false;
                });
                $(this).mouseup(function (login) {
                    if (!($(login.target).parent('#loginButton').length > 0)) {
                        button.removeClass('active');
                        box.hide();
                    }
                });
            });


        </script>
    </head>
    <body>        

        <div class="container-outer">
            <!-- Header -->
            <div class="mkdf-top-bar">
                <div class="mkdf-grid">
                    <div class="mkdf-vertical-align-containers mkdf-33-66">
                        <div class="mkdf-position-left mkdf-top-bar-widget-area">
                            <div class="mkdf-position-left-inner mkdf-top-bar-widget-area-inner">
                                <div class="widget widget_mkd_social_icon_widget mkdf-top-bar-widget">
                                    <div class="mkdf-top-bar-widget-inner"> <a class="mkdf-social-icon-widget-holder mkdf-social_twitter" href="https://twitter.com/" target="_blank"> <span class="mkdf-social-icon-widget social_twitter"></span> </a></div>
                                </div>
                                <div class="widget widget_mkd_social_icon_widget mkdf-top-bar-widget">
                                    <div class="mkdf-top-bar-widget-inner"> <a class="mkdf-social-icon-widget-holder mkdf-social_facebook" href="https://www.facebook.com/" target="_blank"> <span class="mkdf-social-icon-widget social_facebook"></span> </a></div>
                                </div>
                                <div class="widget widget_mkd_social_icon_widget mkdf-top-bar-widget">
                                    <div class="mkdf-top-bar-widget-inner"> <a class="mkdf-social-icon-widget-holder mkdf-social_googleplus" href="https://plus.google.com/" target="_blank"> <span class="mkdf-social-icon-widget social_googleplus"></span> </a></div>
                                </div>
                                <div class="widget widget_mkd_social_icon_widget mkdf-top-bar-widget">
                                    <div class="mkdf-top-bar-widget-inner"> <a class="mkdf-social-icon-widget-holder mkdf-social_linkedin" href="https://linkedin.com/" target="_blank"> <span class="mkdf-social-icon-widget social_linkedin"></span> </a></div>
                                </div>
                            </div>
                        </div>
                        <div class="mkdf-position-right mkdf-top-bar-widget-area">
                            <div class="mkdf-position-right-inner mkdf-top-bar-widget-area-inner">
                                <div  class="widget widget_text mkdf-top-bar-widget">
                                    <div class="mkdf-top-bar-widget-inner">
                                        <div class="textwidget">
                                            <div class="mkdf-icon-list-item mkdf-icon-list-item-default-font-family">
                                                <div class="mkdf-icon-list-icon-holder">
                                                    <div class="mkdf-icon-list-icon-holder-inner clearfix"> <i class="mkdf-icon-font-awesome fa fa-phone " style="font-size:17px"></i></div>
                                                </div>
                                                <p class="mkdf-icon-list-text" style="font-weight: 600;padding-left: 10px"> +91-9717562646</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div  class="widget widget_text mkdf-top-bar-widget">
                                    <div class="mkdf-top-bar-widget-inner">
                                        <div class="textwidget">
                                            <div class="mkdf-icon-list-item mkdf-icon-list-item-default-font-family">
                                                <div class="mkdf-icon-list-icon-holder">
                                                    <div class="mkdf-icon-list-icon-holder-inner clearfix"> <i class="mkdf-icon-font-awesome fa fa-map-marker " style="font-size:17px"></i></div>
                                                </div>
                                                <p class="mkdf-icon-list-text" style="font-weight: 600;padding-left: 10px"> 79, Sector E, pocket 2, Vasant Kunj, New Delhi 110070</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container"><a href="<?php echo $this->url('home') ?>"><img  class="koolguru-logo" src="<?php echo $this->basePath() . "/css_theme/images/koolguru-logo.png"; ?>" alt="logo"/></a></div>
            <header class="mkdf-page-header">
                <div class="mkdf-menu-area">
                    <div class="mkdf-grid">
                        <?php if (isset($roleCode) && ($roleCode == 'sa' || $roleCode == 'aa' || $roleCode == 'st')) { ?>
                            <div class="mkdf-vertical-align-containers">
                                <div class="mkdf-position-right">
                                    <div class="mkdf-position-right-inner">
                                        <nav class="mkdf-main-menu mkdf-drop-down mkdf-default-nav">
                                            <ul id="menu-main-menu" class="clearfix">
                                                <li id="nav-menu-item-751" class="menu-item">
                                                    <a href="<?php echo $this->url('home') ?>" class=" current  no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">Home</span></span></span></a>
                                                </li>
                                                <li id="nav-menu-item-752" class="menu-item">
                                                    <a href="" class=" no_link" data-toggle="dropdown" ><span class="item_outer"><span class="item_inner"><span class="item_text">About Us</span></span><span class="plusicon"></span></span>
                                                    </a>
                                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>">About Us</a></li>
                                                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'mission')); ?>">Mission</a></li>
                                                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'vision')); ?>">Vision</a></li>
                                                    </ul>
                                                </li>
                                                <?php if (isset($roleCode) && ($roleCode == 'sa' || $roleCode == 'aa')) { ?>
                                                    <li id="nav-menu-item-752" class="menu-item">
                                                        <a href="" class=" no_link" data-toggle="dropdown" ><span class="item_outer"><span class="item_inner"><span class="item_text">Question Bank</span></span><span class="plusicon"></span></span>
                                                        </a>
                                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                                            <li><a href="<?php echo $this->url('question', array('action' => 'index')) ?>">Manage Questions</a></li>
                                                            <li><a href="<?php echo $this->url('level', array('action' => 'index')) ?>">Manage Levels</a></li>
                                                        </ul>
                                                    </li>
                                                    <li id="nav-menu-item-752" class="menu-item">
                                                        <a href="" class=" no_link" data-toggle="dropdown" ><span class="item_outer"><span class="item_inner"><span class="item_text">Administration</span></span><span class="plusicon"></span></span>
                                                        </a>
                                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                                            <li><a href="<?php echo $this->url('admin', array('action' => 'contactquery')) ?>">Contact Us Queries</a></li>
                                                            <li><a href="<?php echo $this->url('admin', array('action' => 'studentregister')) ?>">Student Register</a></li>
                                                        </ul>
                                                    </li>
                                                <?php } else { ?>

                                                <?php } ?>
                                                <li id="nav-menu-item-759" class="menu-item">
                                                    <a href="javascript:void(0)" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">Blog</span></span><span class="plus"></span></span></a>
                                                </li>
                                                <li id="nav-menu-item-757" class="menu-item">
                                                    <a href="<?php echo $this->url('logout') ?>" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">LOGOUT</span></span><span class="plus"></span></span></a>
                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        <?php } else { ?>
                            <div class="mkdf-vertical-align-containers">
                                <div class="mkdf-position-right">
                                    <div class="mkdf-position-right-inner">
                                        <nav class="mkdf-main-menu mkdf-drop-down mkdf-default-nav">
                                            <ul id="menu-main-menu" class="clearfix">
                                                <li id="nav-menu-item-751" class="menu-item">
                                                    <a href="<?php echo $this->url('home') ?>" class=" current  no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">Home</span></span></span></a>
                                                </li>
                                                <li id="nav-menu-item-752" class="menu-item">
                                                    <a href="" class=" no_link" data-toggle="dropdown" ><span class="item_outer"><span class="item_inner"><span class="item_text">About Us</span></span><span class="plusicon"></span></span>
                                                    </a>
                                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>">About Us</a></li>
                                                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'mission')); ?>">Mission</a></li>
                                                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'vision')); ?>">Vision</a></li>
                                                    </ul>
                                                </li>
                                                <li id="nav-menu-item-756" class="menu-item">
                                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'contactus')); ?>" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">CONTACT</span></span><span class="plus"></span></span></a>
                                                </li>
                                                <li id="nav-menu-item-757" class="menu-item">
                                                    <a href="<?php echo $this->url('studentlogin') ?>" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">LOGIN</span></span><span class="plus"></span></span></a>
                                                </li>
                                                <li id="nav-menu-item-758" class="menu-item">
                                                    <a href="<?php echo $this->url('student') ?>" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">REGISTER</span></span><span class="plus"></span></span></a>
                                                </li>
                                                <li id="nav-menu-item-759" class="menu-item">
                                                    <a href="javascript:void(0)" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">Blog</span></span><span class="plus"></span></span></a>
                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </header>
            <?php if (isset($roleCode) && ($roleCode == 'sa' || $roleCode == 'aa' || $roleCode == 'st')) { ?>
                <nav class="clearfix pagenav">
                    <a href="#" id="pull"></a>
                    <ul class="clearfix">
                        <li>
                            <a href="<?php echo $this->url('home') ?>">Home</a>
                        </li>
                        <li id="nav-menu-item-752" class="menu-item">
                            <a href="" class=" no_link" data-toggle="dropdown" ><span class="item_outer"><span class="item_inner"><span class="item_text">About Us</span></span><span class="plusicon"></span></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>">About Us</a></li>
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'mission')); ?>">Mission</a></li>
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'vision')); ?>">Vision</a></li>
                            </ul>
                        </li>
                        <?php if (isset($roleCode) && ($roleCode == 'sa' || $roleCode == 'aa')) { ?>
                            <li id="nav-menu-item-752" class="menu-item">
                                <a href="" class=" no_link" data-toggle="dropdown" ><span class="item_outer"><span class="item_inner"><span class="item_text">Question Bank</span></span><span class="plusicon"></span></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('question', array('action' => 'index')) ?>">Manage Questions</a></li>
                                    <li><a href="<?php echo $this->url('level', array('action' => 'index')) ?>">Manage Levels</a></li>
                                </ul>
                            </li>
                            <li id="nav-menu-item-752" class="menu-item">
                                <a href="" class=" no_link" data-toggle="dropdown" ><span class="item_outer"><span class="item_inner"><span class="item_text">Administration</span></span><span class="plusicon"></span></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('admin', array('action' => 'contactquery')) ?>">Contact Us Queries</a></li>
                                    <li><a href="<?php echo $this->url('admin', array('action' => 'studentregister')) ?>">Student Register</a></li>
                                </ul>
                            </li>
                        <?php } else { ?>

                        <?php } ?>
                        <li id="nav-menu-item-759" class="menu-item">
                            <a href="javascript:void(0)" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">Blog</span></span><span class="plus"></span></span></a>
                        </li>
                        <li id="nav-menu-item-757" class="menu-item">
                            <a href="<?php echo $this->url('logout') ?>" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">LOGOUT</span></span><span class="plus"></span></span></a>
                        </li>
                    </ul>
                </nav>
            <?php } else { ?>
                <nav class="clearfix pagenav">
                    <a href="#" id="pull"></a>
                    <ul class="clearfix">
                        <li id="nav-menu-item-751" class="menu-item">
                            <a href="<?php echo $this->url('home') ?>" class=" current  no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">Home</span></span></span></a>
                        </li>
                        <li id="nav-menu-item-752" class="menu-item">
                            <a href="" class=" no_link" data-toggle="dropdown" ><span class="item_outer"><span class="item_inner"><span class="item_text">About Us</span></span><span class="plusicon"></span></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>">About Us</a></li>
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'mission')); ?>">Mission</a></li>
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'vision')); ?>">Vision</a></li>
                            </ul>
                        </li>
                        <li id="nav-menu-item-756" class="menu-item">
                            <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'contactus')); ?>" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">CONTACT</span></span><span class="plus"></span></span></a>
                        </li>
                        <li id="nav-menu-item-757" class="menu-item">
                            <a href="<?php echo $this->url('studentlogin') ?>" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">LOGIN</span></span><span class="plus"></span></span></a>
                        </li>
                        <li id="nav-menu-item-758" class="menu-item">
                            <a href="<?php echo $this->url('student') ?>" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">REGISTER</span></span><span class="plus"></span></span></a>
                        </li>
                        <li id="nav-menu-item-759" class="menu-item">
                            <a href="javascript:void(0)" class=" no_link" ><span class="item_outer"><span class="item_inner"><span class="item_text">Blog</span></span><span class="plus"></span></span></a>
                        </li>
                    </ul>
                </nav>
            <?php } ?>

            <?php echo $this->content; ?>
            <section id="footer_page_links">
                <div class="container">
                    <ul class="nav menu">
                        <li class="deeper parent width-30">
                            <!--<ul class="nav-child unstyled small"><li><a href="/about-us">About Us</a></li><li class="item-175"><a href="/contact-us">Contact Us</a></li><li><a href="/about-us/careers">Careers</a></li><li class="item-313"><a href="" target="_blank">Staff Login</a></li></ul></li><li class="item-178 divider deeper parent">-->
                            <span class="separator">
                                Our Newsletter</span>
                            <ul class="nav-child unstyled small"><li><a href="javascript:void(0)">We are starting our 1st marketing campaign from 15th Feb.... Watch out for our Canope at your college....</a></li></ul></li><li class="item-186 deeper parent">
                            <span class="separator">
                                Information</span>
                            <ul class="nav-child unstyled small">
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'locateus')); ?>">Locate Us</a></li>
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'vision')); ?>">Vision</a></li>
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>">About Us</a></li>
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'mission')); ?>">Mission</a></li>
                                <li><a href="<?php echo $this->url('login'); ?>">Staff Login</a></li>
                                <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'testimonial')) ?>">Testimonials</a></li>
                            </ul></li>
                        <li class="deeper parent"><span class="separator">
                                Our Address</span>
                            <ul class="nav-child unstyled small"><li><a href="javascript:void(0)">
                                        <p>79, Sector E pocket 2</p>
                                        <p>Vasant Kunj</p>
                                        <p>New Delhi 110070</p>                            
                                        <p>India</p>
                                        <p>Phone:+91 9717562646</p>                            
                                        <p>Email: <span><a href="mailto:info@koolguru.co.in">info@koolguru.co.in</a></span></p></a>
                                </li></ul></li>
                        <li class="item-196 deeper parent"><span class="separator">
                                Legal</span>
                            <ul class="nav-child unstyled small">
                                <li>
                                    <a href="#">Privacy Policy</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'faq')); ?>">FAQ's</a>
                                </li>
                            </ul>
                        </li>



                    </ul>

                </div>
                <div class="container footer-contact">
                    <div class="copy_right">
                        <p>&copy; 2015 All Rights Reseverd | Version: 1.0</p>
                    </div>
                    <div class="footer_nav">
                        <ul>
                            <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
                            <li><a href="#">Terms of use</a></li>
                            <li><a href="#">Privacy Policy</a></li>                        
                            <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'contactus')); ?>">Contact</a></li>
                        </ul>
                        <script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=73064553"></script>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </section>


            <?php echo $this->inlineScript() ?>
            <script type="text/javascript" src="<?php echo $this->basePath() . '/js/owl.carousel.js'; ?>"></script>
            <script type="text/javascript">
            $(document).ready(function () {

                $("#owl-demo").owlCarousel({
                    navigation: true, // Show next and prev buttons
                    slideSpeed: 300,
                    paginationSpeed: 400,
                    singleItem: true,
                    autoPlay: true,
                    autoHeight: true

                });

                $("#owl-demo1").owlCarousel({
                    navigation: true, // Show next and prev buttons
                    slideSpeed: 300,
                    paginationSpeed: 400,
                    singleItem: true,
                    autoPlay: true,
                    autoHeight: true

                });

                $("#owl-demo2").owlCarousel({
                    autoPlay: 3000, //Set AutoPlay to 3 seconds

                    items: 3,
                    itemsDesktop: [1199, 3],
                    itemsDesktopSmall: [979, 3]

                });
                $(function () {
                    var pull = $('#pull');
                    menu = $('nav ul');
                    menuHeight = menu.height();

                    $(pull).on('click', function (e) {
                        e.preventDefault();
                        $('nav ul').slideToggle();
                    });

                    $(window).resize(function () {
                        var w = $(window).width();
                        if (w > 320 && menu.is(':hidden')) {
                            menu.removeAttr('style');
                        }
                    });
                });


            });
            </script>
    </body>
</html>
<script src="http://vjs.zencdn.net/5.4.4/video.js"></script>
