<?php
echo $this->doctype();
if (isset($_SESSION['User']['roleCode'])):
    $roleCode = $_SESSION['User']['roleCode'];
endif;
?>

<html lang="en">
    <head>
        <script>var app = {};</script>
        <meta charset="utf-8">
        <?php echo $this->headTitle('KoolGuru') ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/animate.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800,900')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300:700')
//                ->prependStylesheet($this->basePath() . '/css/nav.css')
                ->prependStylesheet($this->basePath() . '/css/slider.css')
                ->prependStylesheet($this->basePath() . '/js/select2/select2.css')
                ->prependStylesheet($this->basePath() . '/js/fancybox/jquery.fancybox.css')
                ->prependStylesheet($this->basePath() . '/js/ajax/libs/jqueryui/1.11.1/themes/smoothness/jquery-ui.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/css/video.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/video.js')
                ->prependFile($this->basePath() . '/js/wow.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/select2/select2.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/fancybox/jquery.fancybox.pack.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/koolguru/custom.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/index.js', 'text/javascript', array())
                ->prependFile($this->basePath() . '/js/jquery.openCarousel.js')
                ->prependFile($this->basePath() . '/js/modernizr.custom.js')
                ->prependFile($this->basePath() . '/js/ajax/libs/jquery.form/3.32/jquery.form.js')
                ->prependFile($this->basePath() . '/js/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js')
                ->prependFile($this->basePath() . '/js/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')

        ;
        ?>



        <script>
            new WOW().init();
        </script>

        <script>
            $(function () {

                var button = $('#loginButton');
                var box = $('#loginBox');
                var form = $('#loginForm');
                button.removeAttr('href');
                button.mouseup(function (login) {
                    box.toggle();
                    button.toggleClass('active');
                });
                form.mouseup(function () {
                    return false;
                });
                $(this).mouseup(function (login) {
                    if (!($(login.target).parent('#loginButton').length > 0)) {
                        button.removeClass('active');
                        box.hide();
                    }
                });
            });


        </script>
    </head>
    <body>        
        <!-- Header -->
        <div class="header">    
            <div class="header_top">
                <div class="container">

                    <div class="headertop_nav">
                        <?php if (isset($roleCode) && ($roleCode == 'sa' || $roleCode == 'aa')) { ?>
                            <div class="navigation">	
                                <div>
                                    <ul class="nav navbar-nav">
                                        <li>
                                            <a href="<?php echo $this->url('home') ?>" class="dropdown-toggle" ><span class="home-icon"></span><?php echo $this->translate('Home', __NAMESPACE__) ?></a>
                                        </li>
                                        <li class="dropdown">
                                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><span class="qualification-icon"></span>Pathways<span  		
                                                    class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <!--<li><a href="<?php // echo $this->url('qualification', array('action' => 'index'))    ?>">View</a></li>-->
                                                <!--<li><a href="<?php // echo $this->url('qualificationrequest', array('action' => 'index'))    ?>">Requests</a></li>-->
                                                <!--<li><a href="javascript:void(0);">Renewals</a></li>-->
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><span class="trainee-icon"></span>Student
                                                <span class="caret" ></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <!--<li><a href="<?php // echo $this->url('trainee', array('action' => 'index'))    ?>">Manage Trainees</a></li>-->
                                                <!--<li><a href="javascript:void(0);">Update Enrollment Status</a></li>-->
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><span class="cohort-icon"></span>
                                                Question Bank<span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="<?php echo $this->url('question', array('action' => 'index')) ?>">Manage Questions</a></li>
                                                <li><a href="<?php echo $this->url('level', array('action' => 'index')) ?>">Manage Levels</a></li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><span class="booking-icon"></span>
                                                Quiz<span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <!--<li class="dropdown-header">Assessment</li>-->
                                                <!--<li><a href="<?php // echo $this->url('assessment', array('action' => 'index'))    ?>">Book Assessment</a></li>-->
                                                <!--<li class="divider"></li>-->
                                                <!--<li><a href="<?php // echo $this->url('externalverifierbooking', array('action' => 'index'))    ?>">External Verifier Visit</a></li>-->                                            
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                                <span class="admin-icon"></span>Administration<span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">

                                            </ul>
                                        </li>
                                    </ul>
                                </div>			
                            </div>

                        <?php } else { ?>
                            <ul>
                                <li>Call Us </li>
                                <li> :(000) 123-456 </li> 
                                <li> Email us : </li> 
                                <li>info@koolguru.co.in</li> 
                            </ul>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="header_bottom">
                <div class="container">	 			
                    <div class="logo">
                        <h1><a href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath() . '/img/logo.png' ?>"><span></span></a></h1>
                    </div>	
                    <?php if (isset($roleCode) && ($roleCode == 'sa' || $roleCode == 'aa' || $roleCode == 'st')) { ?>
                        <div class="header-top-right">
                            <ul class="notifications">
                                <li id="header-user-dropdown" class=" dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                        <span class="user-icon"></span>
                                        <span class="grey-caret"></span></a>
                                    <ul class="dropdown-menu user-menu" role="menu">
                                        <li><?php echo $_SESSION['User']->fname . ' ' . $_SESSION['User']->lname; ?><span class="user-email"><?php echo $_SESSION['User']->email; ?></span></li>
                                        <li>
                                            <a href="javascript:void(0)" class="change-password">Change Password</a>
                                        </li>
                                        <li class="user-menu-footer">
                                            <!--<a href="javascript:void(0);" class="help"><span class="help-icon"></span>Help</a>-->
                                            <a href="<?php echo $this->url('logout') ?>" class="logout-btn">Logout</a>
                                        </li>
                                    </ul>
                                </li>

                            </ul> 
                        </div>
                    <?php } else { ?>
                        <div class="header-top-right">
                            <div class="login_box">
                                <div id="loginContainer">
                                    <a href="<?php echo $this->url('studentlogin') ?>" class="logout-btn">Login</a>
                                </div>
                            </div> 
                        </div>
                    <?php } ?>
                </div>
            </div>	

        </div>
    </div>
    <!-- Ends Header -->


    <?php echo $this->content; ?>


    <div class="footer">
        <div class="container">   	 
            <div class="footer_top">
                <div class="row">
                    <div class="col-md-4 footer_grid">
                        <h4>Receive our Newsletter</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    </div>
                    <div class="col-md-4 footer_grid">
                        <h4>Info</h4>
                        <div class="footer-list">
                            <ul>
                                <li class="list_top">                                    
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'locateus')); ?>">Locate Us</a>
                                </li>
                                <li class="list_top">                                    
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>">About Us</a>
                                </li>
                                <li class="list_top">
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'vision')); ?>">Vision</a>
                                </li>
                                <li class="list_top">
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'mission')); ?>">Mission</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 footer_grid">
                        <h4>Our Address</h4>
                        <div class="company_address">
                            <p>79, Sector E pocket 2
                            <p>Vasant Kunj</p>
                            <p>New Delhi 110070</p>                            
                            <p>India</p>
                            <p>Phone:(00) 222 666 444</p>                            
                            <p>Email: <span><a href="mailto:info@koolguru.co.in">info@koolguru.co.in</a></span></p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="footer_bottom">
                <div class="copy_right">
                    <p>&copy; 2015 All Rights Reseverd | Version: Beta 1.0</p>
                </div>
                <div class="footer_nav">
                    <ul>
                        <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
                        <li><a href="#">Terms of use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'contactus')); ?>">Contact</a></li>
                    </ul>
                </div>
                <div class="clearfix"></div>
                <script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=73064553"></script>
            </div>
        </div>
    </div>
    <?php echo $this->inlineScript() ?>
</body>
</html>
<script src="http://vjs.zencdn.net/5.4.4/video.js"></script>
