<?php
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
$title = 'Manage Blogs';
$default_order = 'ASC';
$url_order = $this->order == 'ASC' ? 'DESC' : 'ASC';
$query = '';
//asd($users);
if (isset($data['search_box'])) {
    $query .= '&search_box=' . $data['search_box'];
}
if (isset($_SESSION['User']['roleCode'])):
    $roleCode = $_SESSION['User']['roleCode'];
endif;
if (!$this->isAjax) {
    ?>
    <section class="sub-header">
        <div class="container">


            <div class="sub-header-title">
                <span class="manage-center-icon"></span>
                <h1 class="h1"><?php echo $this->escapeHtml($title); ?>   
                    <?php
                    /* Adding Breadcrumb */
                    echo $this->navigation('navigation')
                            ->breadcrumbs()
                            ->setMinDepth(0)
                            ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                    ?>
                </h1>
            </div>
            <?php if ((isset($roleCode)) && ($roleCode == 'sa')) { ?>
                <div class="sub-header-actions">
                    <!--<a class="big-btn green-btn import-btn" id="import_center" href="#">IMPORT</a>-->
                    <a class="big-btn green-btn" href="<?php echo $this->url('blog', array('action' => 'add')); ?>">CREATE</a>
                </div>
            <?php } ?>

        </div>
    </section>

    <div class="container">

        <?php
        $errorflashMessage = $this->flashMessenger()->getCurrentErrorMessages();
        $successflashMessage = $this->flashMessenger()->getCurrentSuccessMessages();
        if (empty($errorflashMessage) && !empty($successflashMessage)) {
            ?>
            <div id="global-success-msg-page" class="global-page-success">
                <?php
                foreach ($successflashMessage as $succMsg) {
                    echo $succMsg;
                }
                ?>

            </div>
        <?php
        } else {
            if (!empty($errorflashMessage)) {
                ?>
                <div id="global-error-msg-page"   class="global-page-error"><?php
                    foreach ($errorflashMessage as $errMsg) {
                        echo $errMsg;
                    }
                    ?></div>
            <?php
            }
        }
        ?>
        <?php
        $search_form = $this->form;
        $search_form->setAttribute('action', $this->url('blog', array('action' => 'bloglist')));
        $search_form->prepare();
        echo $this->form()->openTag($search_form);
        ?>
        <div class="action-table">
            <div class="filter-table">
                <div class="listing-counts-per-page">
                    <div class="listing-search-dropdown pull-left">
                        <span>
                            <?php
                            echo $this->formRow($search_form->get('list_count'));
                            ?>
                        </span>
                    </div>
                </div>
                <?php
                echo $this->formRow($search_form->get('order_by'));
                echo $this->formRow($search_form->get('order'));
                ?>
            </div>
            <div class="search-table">

                <span class="search-holder">
                    <?php
                    echo $this->formRow($search_form->get('search_box'));
                    echo $this->formRow($search_form->get('search_box_value'));
                    echo $this->formRow($search_form->get('searchbutton'));
                    echo $this->form()->closeTag();
                    ?>
                </span>


            </div>
        </div>
        <?php
    }
    ?>
    <div id="grid-list">
<?php if ($this->row_count == 0) { ?>
            <table  class="table center-listing table-disable">
                <thead>
                    <tr>
                        <th class="id">
                            <a href="javascript:void(0);">ID<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="name">
                            <a href="javascript:void(0);">Title<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="type">
                            <a href="javascript:void(0);">POST<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="type">
                            <a href="javascript:void(0);">STATUS<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        
                        <th class="type">
                            <a href="javascript:void(0);">Created/Updated On<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="type">
                            Created/Updated By
                        </th>
                        <?php if ($roleCode == 'sa') { ?>
                            <th class="actions">ACTIONS</th>
    <?php } ?>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="7"><div class="no-records"><span class="info-icon"></span>No records found !</div></td>
                    </tr>
                </tbody>
            </table>
<?php } else { ?>
            <table  class="table center-listing">
                <thead>
                    <tr>
                        <th class="id">
                            <a href="javascript:void(0);" onclick="grid.sort('id', '<?php echo ($this->order_by == 'id') ? $url_order : $default_order; ?>');">ID<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="name">
                            <a href="javascript:void(0);" onclick="grid.sort('title', '<?php echo ($this->order_by == 'title') ? $url_order : $default_order; ?>');">Title<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="type">
                            <a href="javascript:void(0);" onclick="grid.sort('post', '<?php echo ($this->order_by == 'post') ? $url_order : $default_order; ?>');">POST<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="type">
                            <a href="javascript:void(0);" onclick="grid.sort('status', '<?php echo ($this->order_by == 'status') ? $url_order : $default_order; ?>');">Status<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="type">
                            <a href="javascript:void(0);" onclick="grid.sort('updated_at', '<?php echo ($this->order_by == 'updated_at') ? $url_order : $default_order; ?>');">Created/Updated On<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i></a>
                        </th>
                        <th class="type">
                            Created/Updated By
                        </th>
                        <?php if ((isset($roleCode)) && ($roleCode == 'sa')) { ?>
                            <th class="actions">ACTIONS</th>
    <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->paginator as $question) :
                        ?>
                        <tr>
                            <td class="id"><a class="blue-anchor" href="<?php echo $this->url('subject', array('action' => 'view', 'id' => $question['id'])); ?>"><?php echo $this->escapeHtml($question['id']); ?></a></td>
                            <td class="name"><?php echo $this->escapeHtml($question['title']); ?></td>
                            <td class="type"><?php echo $this->escapeHtml($question['post']); ?></td> 
                            <td class="type status"><?php echo ($this->escapeHtml($question['status'])==1) ? 'Approved' : 'Not Approved'; ?></td> 
                            <td class="type"><?php echo date('h:i A j F Y',$question['updated_at']);?></td>
                            <td class="type"><?php echo ($question['is_student'] == 1) ? $users['is_student'][$question['updated_by']] : $users['is_admin'][$question['updated_by']];?></td>
                             <?php if ((isset($roleCode)) && ($roleCode == 'sa')) { ?>
                                <td class="actions">
                                    <?php if($question['status'] == 0){?>
                                    <a class="big-btn green-btn" href="javascript:void(0)" blog_id='<?php echo $question['id']?>' status="1" onclick="updatestatus(this)">Approve</a>
                                    <?php }else{ ?>
                                    <a class="big-btn green-btn" href="javascript:void(0)" blog_id='<?php echo $question['id']?>' status="0" onclick="updatestatus(this)">Dis Approve</a>
                                    <?php } ?>
                                </td>
                        <?php } ?>
                        </tr>

                        <?php
                    endforeach;
                    ?>
                </tbody>
            </table>
            <div class="listing-counts-per-page">
                <div class="listing-search-dropdown pull-left">
                    <?php
                    if (!$this->isAjax) {
//                                    echo $this->formRow($search_form->get('list_count'));
//                                    echo $this->form()->closeTag();
                        //$this->inlineScript()->appendFile('js/sss_js/center.js');
                    }
                    ?>
                </div>
                <div class="entries-count pull-right">
                    <?php
                    if ($this->row_count > ($this->list_count * $this->page)) {
                        ?>
                        <span class="entries">Showing <?php echo 1 + ($this->list_count * ($this->page - 1)); ?> to <?php echo $this->list_count * ($this->page); ?> of <?php echo $this->row_count; ?> entries.</span>
                        <?php
                    } else {
                        ?>
                        <span class="entries">Showing <?php echo 1 + ($this->list_count * ($this->page - 1)); ?> to <?php echo $this->row_count; ?> of <?php echo $this->row_count; ?> entries.</span>                
    <?php } ?>
                </div>
            </div>

            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator, 'sliding',
                    // the partial to use to render the control
                    array('partial/paginator.phtml', 'subject'),
                    // the route to link to when a user clicks a control link
                    array(
                'route' => 'blog',
                'routeParams' => array('action' => 'bloglist'),
                'jsFunction' => 'grid.list',
                'query' => $this->data
                    )
            );
            ?>

            <?php
        }
        $this->inlineScript()->appendFile('../js/koolguru/searchgrid.js');
        ?>

    </div>


</div>
<script>
function updatestatus(obj){
    var  status = $(obj).attr('status');
    var  blog_id = $(obj).attr('blog_id');
    if(status == 1){
        $(obj).parent().parent().find('.status').text('Approved');        
        $(obj).text('Dis Approve');
        $(obj).attr('status',0);
        
    }else{
        $(obj).parent().parent().find('.status').text('Not Approved');
        $(obj).text('Approve');
        $(obj).attr('status',1);
    }
    
    var url = '<?php echo $this->basePath() . '/updatestatus'; ?>';
    $.ajax({url: url, data: 'status=' + status + '&blog_id=' + blog_id, success: function (result) {

    }});
}
</script>
