<div class="staff">
    <div class="reservation_top">
        <div class="container">          	 
            <h3 class="hist">About Us</h3>
            <div class="row">
                <div class="col-sm-6">
                    <img src="<?php echo $this->basePath() . '/img/h1.jpg' ?>" class="img-responsive" alt=""/>
                </div>
                <div class="col-sm-6 history_grid">
<!--                    <h3><a href="#">Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl</a></h3>-->
                    <p>We are self-motivated and hard-working group of individuals and our goal is to bring about a revolution in the education by making it interactive using state of art technology to benefit the larger sections of the society. Results would be our driving force.</p>
                                    <a href="#" title="Online Reservation" class="btn btn-primary btn2 btn-normal btn-inline " target="_self">Read More</a>
                </div>
            </div>
        </div>
    </div>
</div>