<div class="staff">
    <div class="reservation_top">
        <div class="container">          	 
            <h3 class="hist">About Us</h3>
            <div class="row row-login">
                <div class="col-sm-6">
                    <img src="<?php echo $this->basePath() . '/img/AboutUs.jpg' ?>" class="img-responsive" alt=""/>
                </div>
                <div class="col-sm-6 history_grid">
<!--                    <h3><a href="#">Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl</a></h3>-->
                    <p>We are the team of professionals from IIMs, IIT & elite management colleges &with rich experience in teaching. We are simply passionate to share about our learning experience &believe in utilization of technology for enhancing the scope of students. We are the experts whoknow what goes on in our minds when we actually are there in the exam centre or set a question paper (been there, done that). Teaching a concept in a class, and utilizing it in a centre are way different. We teach you the exam temperament to cope up with the unwanted mistake we generally do in the exams.</p>
<!--                                    <a href="#" title="Online Reservation" class="btn btn-primary btn2 btn-normal btn-inline " target="_self">Read More</a>-->
                </div>
            </div>
        </div>
    </div>
</div>