<div class="main"> 
    <div class="reservation_top">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="contact_left">
                        <h3>Contact Info</h3>
                        <iframe class="map" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=United+Kingdom&amp;aq=0&amp;oq=un&amp;sll=37.0625,-95.677068&amp;sspn=48.956293,107.138672&amp;ie=UTF8&amp;hq=&amp;hnear=United+Kingdom&amp;ll=55.378051,-3.435973&amp;spn=135.795411,68.554687&amp;t=m&amp;z=2&amp;output=embed"> </iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=United+Kingdom&amp;aq=0&amp;oq=un&amp;sll=37.0625,-95.677068&amp;sspn=48.956293,107.138672&amp;ie=UTF8&amp;hq=&amp;hnear=United+Kingdom&amp;ll=55.378051,-3.435973&amp;spn=135.795411,68.554687&amp;t=m&amp;z=2" style="color:#666;font-size:12px;text-align:left"> </a></small>
                        <address class="address">
                            <p>79, Sector E pocket 2
                            <p>Vasant Kunj</p>
                            <p>New Delhi 110070</p>                            
                            <p>India</p>
                            <p>Phone:+91 9171562646</p>                            
                            <p>Email: <span><a href="mailto:info@koolguru.co.in">info@koolguru.co.in</a></span></p>
                            <ul class="social-network social-circle">
                            <!--<li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>-->
                                <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </address>
                    </div>
                </div>
                <div class="col-md-7 contact_right">
                    <h3>Contact Form</h3>
                    <div class="contact-form">
                        <form method="post" action="contact-post.html">
                            <input type="text" class="textbox" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {
                                        this.value = 'Name';
                                    }">
                            <input type="text" class="textbox" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {
                                        this.value = 'Email';
                                    }">
                            <textarea value="Message" onfocus="this.value = '';" onblur="if (this.value == '') {
                                        this.value = 'Message';
                                    }">Message</textarea>
                            <input type="submit" value="Send">
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>