<style>
    #content-2{
        position: initial !important;
    }
    object{
        visibility: visible;
        position: inherit !important;
         
   }
</style>
<div class="main"> 
    <div class="reservation_top">
        <div class="container">
            <main>

                <label for="tab1" id='tab-1' class="kooltab" onclick="app.demoquiz.openTag(1)">About Chapter</label>                
                <label for="tab2" id='tab-2' class="kooltab" onclick="app.demoquiz.openTag(2)"><span>Chapter Presentation</span></label>                
                <label for="tab3" id='tab-3' class="kooltab" onclick="app.demoquiz.openTag(3)">Exercise</label>                
                <label for="tab4" id='tab-4' class="kooltab" onclick="app.demoquiz.openTag(4)">Quiz</label>


                <div class="tabs" id='content-1'>
                    <br>
                    <div>
                        <?php echo $demochapter[0]['chapter_content']?>
                    </div>
                </div>

                <!-- Tab for verbal ability -->
                <div class="tabs" id='content-2'>
                    <br>
                    <div id='media-player'>
                            <video id='media-video' controls>
                                <source src="http://koolguru.co.in/video/Quadratic.mp4" type='video/mp4'>
                                <?php 
                                    $ppt = '';
                                    if(!empty($demochapter)){
                                        $ppt = $demochapter[0]['subject_id'].'-'.$demochapter[0]['chapter_id'];
                                        $ppt .= '.mp4';
                                    }
                                ?>
                                <source src="http://koolguru.co.in/ppt/<?php echo $ppt;?>" type='video/mp4'>
                            </video>
                            <div id='controls'>
                                <progress id='progress-bar' min='0' max='100' value='0'>0% played</progress>
                                <button id='replay-button' class='replay' title='replay' onclick='resetPlayer();'>Replay</button>
                                <button id='play-pause-button' class='play' title='play' onclick='togglePlayPause();'>Play</button>
                                <button id='stop-button' class='stop' title='stop' onclick='stopPlayer();'>Stop</button>
                                <button id='volume-inc-button' class='volume-plus' title='increase volume' onclick='changeVolume("+");'>Increase volume</button>
                                <button id='volume-dec-button' class='volume-minus' title='decrease volume' onclick='changeVolume("-");'>Decrease volume</button>
                                <button id='mute-button' class='mute' title='mute' onclick='toggleMute("true");'>Mute</button>
                                <button id='Autopause-button' class='pause' title='pause' onclick='toggleAutopause("true");'>pause</button>	
                            </div>
                        </div>
                </div>
                <!-- Tab for verbal ability -->
                <div class="tabs" id='content-3'>
                </div>


                <div class="tabs" id='content-4'>
                </div>
            </main>            
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
//        (function () {
//            var ldr = new ispring.presenter.loader.FlashPresentationLoader();
//            ldr.load("ppt/Quadratic Euqations.swf", "content-2", "FlashPresentation", 640, 480);
//        })();
        var tab = new Array();
        var enabletabcontent = new Array();
        tab = [1, 1, 0, 0];
        enabletabcontent = [1, 1, 0, 0];
        app.demoquiz.enabletab = tab;
        app.demoquiz.enabletabcontent = enabletabcontent;

        $('.kooltab').each(function () {
            var tabid = $(this).attr('id');
            tabid = tabid.replace("tab-", "");
            app.demoquiz.hidetab(parseInt(tabid));
        });

        console.log(app.demoquiz.enabletabcontent);
        $.each(app.demoquiz.enabletabcontent, function (index, value) {
            if (value == 1) {
                $('#tab-' + (index + 1)).addClass('enabletab');
                $('#tab-' + (index + 1)).click();
            }
        });

        $.each(app.demoquiz.enabletab, function (index, value) {
            if (value == 1) {
                $('#tab-' + (index + 1)).addClass('activetab');
            }
        });



//        app.studentTab.hidetab(1);
//        app.studentTab.hidetab(2);
//        app.studentTab.hidetab(3);
//        app.studentTab.hidetab(4);
//        app.studentTab.applytabbing(app.studentTab.enabletab);
//        app.studentTab.enableTabContent();
    });
</script>
