<div class="main"> 
    <div class="reservation_top">
        <div class="container">
            <main>

                <label for="tab1" id='tab-1' class="kooltab" onclick="app.studentTab.openTag(1)">Chapter Video</label>                
                <label for="tab2" id='tab-2' class="kooltab" onclick="app.studentTab.openTag(2)"><span>Chapter Presentation</span></label>                
                <label for="tab3" id='tab-3' class="kooltab" onclick="app.studentTab.openTag(3)">Exercise</label>                
                <label for="tab4" id='tab-4' class="kooltab" onclick="app.studentTab.openTag(4)">Quiz</label>

                
                <div class="tabs" id='content-1'>
                    tab1
                </div>

                <!-- Tab for verbal ability -->
                <div class="tabs" id='content-2'>
                    tab 2
                </div>
                
                <!-- Tab for verbal ability -->
                <div class="tabs" id='content-3'>
                    tab 3
                </div>

                
                <div class="tabs" id='content-4'>
                        tab4
                </div>
            </main>            
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var tab = new Array();
        var enabletabcontent = new Array();
        tab = [<?php echo '"' . implode('","', $enableTab) . '"' ?>];
        enabletabcontent = [<?php echo '"' . implode('","', $enableTabContent) . '"' ?>];        
        app.studentTab.enabletab = tab;   
        app.studentTab.enabletabcontent = enabletabcontent;
        
        $('.kooltab').each(function(){
            var tabid = $(this).attr('id');
            tabid = tabid.replace("tab-", "");
            app.studentTab.hidetab(parseInt(tabid));
        });
        
        $.each(app.studentTab.enabletabcontent, function( index, value ) {            
            if(value == 1){
                $('#tab-'+(index+1)).addClass('enabletab');
                $('#tab-'+(index+1)).click();
            }
        });
        
        $.each(app.studentTab.enabletab, function( index, value ) {            
            if(value == 1){
                $('#tab-'+(index+1)).addClass('activetab');
            }
        });
        

        
//        app.studentTab.hidetab(1);
//        app.studentTab.hidetab(2);
//        app.studentTab.hidetab(3);
//        app.studentTab.hidetab(4);
//        app.studentTab.applytabbing(app.studentTab.enabletab);
//        app.studentTab.enableTabContent();
    });
</script>
