<div class="staff">
    <div class="reservation_top">
        <div class="container">          	 
            <h3 class="hist">FAQ'S</h3>
            <div class="row">
               <!-- <div class="col-sm-6">
                    <img src="<?php echo $this->basePath() . '/img/AboutUs.jpg' ?>" class="img-responsive" alt=""/>
                </div>-->
                <div class="col-sm-12 history_grid faq">
<strong>1.  How do we contact Koolguru in case we need some more information?</strong>
You can drop us an email at info@koolguru.co.in or give us a call at 9171562646. Or, you can chat with us (during specific office hours) from the chat window on this website. For any technical issues email at admin@koolguru.co.in



<strong>2.  The online CAT Course - is this alone sufficient to crack the CAT?</strong>
Most definitely, yes. The online course offers clear explanation for all the key concepts. The study material gives ample room for practice and the mock CAT series gets you geared for the actual exam. To Supplement that, We have a few Classrooms Sessions



<strong>3.  How is Koolguru Course better than classroom coaching or other Online CAT program?</strong>
The obvious advantages are clear - a student can learn anywhere, any time and at his/her pace. One does not need proper network connections for the content to buffer. So Basically, whether you ina metro, or in a tunnel or lift, you can still study. But beyond these, the one point that is absolutely crucial is the quality of teaching. 
Vatan is a graduate from IIM A who has been training students for CAT who has been taking classes for CAT since 2008. 
Abhijith is Graduate from IIM B and Ankur is a graduate from IIFT.
We believe that the way we teach is the best way to teach and it is this confidence that has made us offer so many free classes. One go at any of our free classes will convince you that we teach really well.

<strong>4.  How do we get our doubts clarified?</strong>
You can send an email to info@koolguru.co.in We usually reply within 2-3 days. If it is a simple enough question, we will send a reply via email. If it requires more detailed explanation, we can clarify that in the classroom Session. If it is a key point, we will include it as part of the course and send you an email saying "Thanks".



<strong>5.  What are the technical specifications my machine needs to have for the CAT Online course to work?</strong>
Part 1 - Laptop - You will need to have an internet connection, preferably at a speed of around 1 MBPS or better. (the course runs even at speeds lower than that). The videos load only on the Chrome browser. So, the course can only be learnt using Chrome. The simplest test to see if the specifications are met is to try loading some video from youtube on a Chrome browser. If your computer + internet connection lets you watch a video from youtube, you should be able to view everything from the online course from Koolguru.
Part2 - Mobile - Android 4.4 Minimum with around 500mb internal memory free. Screen Size of 4 inches and network/wifi connection once in a day.



<strong>6.  Can we view the videos more than once?</strong>
Yes. Each video can be viewed any number of times.


………………………………………...



<strong>7.  You state repeatedly that the Online CAT course has been designed to help own learn at one's own pace. How so?</strong>
The online CAT Course at 2IIM has been constructed as a mixture of slide-decks, videos and quizzes. An average class that is pegged to be covered in, say, around 2.5 hours for the above-average student will comprise of ~80 slides interspersed with around 8-10 videos. The videos are all of 4-10 minutes length and each video focuses on a separate idea. So, if a student is comfortable with 5 of the 8 ideas discussed in the topic, he/she can skip these videos. Student can get to each subsequent slide by pressing "Next" and the speed is entirely governed by the student.
Apart from this, there are on an average two checkpoint quizzes per topic, each with 6-8 questions. These are simple practice questions to help consolidate the idea. For these also, detailed slide-deck presentations are available, but the student has the option of skipping these if she is comfortable with the question.
Beyond this, there is a timed Prep-Edge quiz that gives questions at the level of difficulty seen in CAT. These also come with detailed slide-deck solutions. Some of the trickier ones have video solutions as well. Student can choose to skip the solution, rush through the slides, or listen to the videos.
Since we give so much choice over picking the medium for the student, the flexibility over speed is established. A beginner can go through all videos, all solutions in detail, both checkpoint quizzes at his/her own speed, and the prep edge questions after doing some more practice. If done this way, the time taken would be around 5 hours for the class.
Someone who has taken CAT before and knows most of the basics can rush through the slides, listen in on the 4 most critical videos, speed through the checkpoint quizzes and focus on taking the Prep Edge quizzes with utmost seriousness. This 'expert' can finish the topic in less than 75 minutes.
The flexibility over speed is particularly useful while revisiting a topic. You can directly zone in on the 2-3 topics and 4-5 questions that you want to revisit, see 3 key videos and be done with the topic. Some of our students have been absolutely thrilled with the pace at which one can revise with the online product.




<strong>8.  You claim to be the best online CAT Preparation Course. How do you know this?</strong>
This one is easy. In our minds, we are probably the only one offering an Online CAT Preparation Course. We offer slide-decks, videos, check-point quizzes and CAT-Level Tests. Most products available are either test series, e-books or recorded classroom lectures. In our mind, none of these qualify as an online course. Online Preparation for CAT has to involve more than reading a bunch of PDFs on a laptop.
Any recorded video of length more than 15 minutes is more or less worthless. Research tells us that people struggle to watch even entertainment videos if they are more than 12 minutes long. (Imagine that, if one struggles to watch Amitabh Bachan for 12 minutes, what are odds of watching a tutor in a 60 minute long video?).
We have spent an inordinate amount of time and energy in designing this course. At every stage, we have worn the hat of a student and brought in the technology that works for each specific idea. The starting point has been the student requirement, and not the technology. This is why we went down the route of using screen capture videos and not live videos. Screen capture videos de-emphasize the teacher and bring the content to the forefront. (This hurts us while trying to market the product). But screen capture gives us two massive advantages - 1) Video size is small. Our videos on a per-minute basis are about one-fourth of the size of the videos on youtube. So, if you have an internet connection that lets you watch stuff of youtube you can most definitely take this course and 2) We can write equations and use a digital pen to highlight key ideas without worrying about camera focus.







<strong>9.  What is the size of the videos? Can we watch it with even a 1MBPs connection?</strong>
As we have mentioned elsewhere in this section, our videos on a per-minute basis are about one-fourth of the size of the videos on youtube. So, if you have an internet connection that lets you watch stuff of youtube you can most definitely take this course. Screen capture technology gives us the option of keeping video length short. This is why we have built the entire content on this model.



<strong>10.  What technology have you used for the videos?</strong>
As far as the online CAT Course is concerned, we have used screen-capture technology for most parts. For recording the videos, we work with a Software called as Blueberry; an alternative Software called Camtasia is also pretty good. Our online tech platform provider is Learnyst. They might use some hi-funda technology to create the platform, but they created a simple enough interface for us to use.



<strong>11.  You have disclosed the tech provider, technology and given all the information up front here. Are you not worried that someone will mimic the online CAT Course?</strong>
We are very generous that way.
Jokes apart, the largest value in the online CAT course sits in the pedagogy. The value lies in
1) the way we have created the course,
2) the people who have created the course and
3) the quality of the content.
We have built the entire content with a team of 3 teachers. They have distilled years of teaching experience to come up with a well-thought out pedagogy that uses technology well. We have not used technology for the sake of using some fancy bits. We have found the tech pieces that the course demanded, not the other way around. That value which our teachers bring to the table cannot be replicated easily.
                </div>
            </div>
        </div>
    </div>
</div>