<div class="staff">
    <div class="reservation_top">
        <div class="container">          	 
            <h3 class="hist">Locate Us</h3>
            <div class="row">
                <iframe
                            class="map" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyALEX1UUmTZWFjIy-8p45Ee6tz6Y7CDJwo
                            &q=28.537691, 77.129936" allowfullscreen>
                        </iframe>
            </div>
        </div>
    </div>
</div>