<div class="staff">
    <div class="reservation_top">
        <div class="container">          	 
            <h3 class="hist">Mission</h3>
            <div class="row row-login">
                <div class="col-sm-6">
                    <img src="<?php echo $this->basePath() . '/img/mission.jpg' ?>" class="img-responsive" alt=""/>
                </div>
                <div class="col-sm-6 history_grid">
<!--                    <h3><a href="#">Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl</a></h3>-->
                    <p>“Innovate to Educate” With this Slogan in mind, KoolGuru is here to revolutionize the education process & learning methodology by introducing technology enabled virtual ways to impart worthy knowledge. For those who feel that distance is a barrier to their higher education, KoolGuru is the right choice for them. For us Education is pure passion not an industry. We are also the advocates of paperless journey to learning. Let’s go green a little.</p>
<!--                                    <a href="#" title="Online Reservation" class="btn btn-primary btn2 btn-normal btn-inline " target="_self">Read More</a>-->
                </div>
            </div>
        </div>
    </div>
</div>