<div class="staff">
    <div class="reservation_top">
        <div class="container">          	 
            <h3 class="hist">Mission</h3>
            <div class="row">
                <div class="col-sm-6">
                    <img src="<?php echo $this->basePath() . '/img/mission.jpg' ?>" class="img-responsive" alt=""/>
                </div>
                <div class="col-sm-6 history_grid">
<!--                    <h3><a href="#">Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl</a></h3>-->
                    <p>“Whenever you are in doubt or your self becomes too much on you,apply the following test...Recall the face of the poorest and the weakest man you have seen and ask yourself..if the step you contemplate is going to be of any use to him”....Mr. M. K. Gandhi
Our mission is to make education benefit every single individual in the most effective way.
</p>
<!--                                    <a href="#" title="Online Reservation" class="btn btn-primary btn2 btn-normal btn-inline " target="_self">Read More</a>-->
                </div>
            </div>
        </div>
    </div>
</div>