<style>
    .wrapper { 
        border : 2px solid #000; 
        overflow:hidden;
    }

    .wrapper div {
        min-height: 200px;
        padding: 10px;
    }
    #one {
        background-color: rgba(12, 20, 74, 0.75);
        float:left; 
        margin-right:20px;
        width:65%;
        border-right:2px solid #000;
        color: #FFF;
    }
    #two { 
        background-color: white;
        overflow:hidden;
        margin:10px;
        /*border:2px dashed #ccc;*/
        min-height:170px;
    }

    @media screen and (max-width: 400px) {
        #one { 
            float: none;
            margin-right:0;
            width:auto;
            border:0;
            border-bottom:2px solid #000;    
        }
    }
</style>
<?php
if (isset($_SESSION['User']['roleCode'])):
    $roleCode = $_SESSION['User']['roleCode'];
endif;
?>
<!--<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
<?php
$title = 'Package Details';
$this->headTitle($title);
?>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>

<?php
/* Adding Breadcrumb */
//                echo $this->navigation('navigation')
//                        ->breadcrumbs()
//                        ->setMinDepth(0)
//                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
?>
            </h1>
        </div>
    </div>
</section>-->

<div class="container">
    <div class="forms">
        <div class="">
            <div class="wrapper">
                <div id="one">
                    <ul>
                        
                        <input type="hidden" id="packageId" name="packageId" value="<?php echo $id; ?>"/>
                        <li class="package-title">
                            <img class="" src="/koolguruweb/public/css_theme/images/koolguru-logo.png" alt="logo">
                            <?php echo $package[0]['title']; ?>
            <!--                <span class="separator-img"></span>
                            <span><a href="javascript:void(0)">BUY NOW</a></span>-->
                        </li>
                        <li title="relevant for" class="package-relevant"><?php
                            if (!empty($package[0]['relevant_for'])) {
                                $userGetsArr = explode(',', $package[0]['relevant_for']);
                                echo '<br/>';
                                echo '<ul>';
                                ?>
                            <li><span class="package-headers"> RELEVANT FOR</span></li>
                            <span class="package-text">
                                <?php
                                foreach ($userGetsArr as $gets) {
                                    echo '<li>';
                                    echo $gets;
                                    echo '</li>';
                                }
                                echo '</ul>';
                            }
                            ?></span>
                        <ul>

                            <li>
                                <span title="Duration"></span><span class="package-headers"> DURATION<br/></span><span class="package-text"> <?php echo $package[0]['duration'] ?></span>
                            </li>
                            <li>
                                <span title="Price"></span><span class="package-headers"> PRICE<br/></span><span class="package-text"><?php echo $package[0]['price'] ?></span>
                            </li>
                            <li>
                                <span title="Face to Face Class-room"></span><span class="package-headers"> FACE TO FACE CLASSROOM<br/></span><span class="package-text"><?php echo $package[0]['ff_classroom'] ?></span>
                            </li>
                            <li>
                                <span title="advantage"></span><span class="package-headers"> ADVANTAGE <br/></span><span class="package-text"><?php
                                    if (!empty($package[0]['advantage'])) {
                                        $userGetsArr = explode(',', $package[0]['advantage']);
                                        echo '<ul>';
                                        foreach ($userGetsArr as $gets) {
                                            echo '<li>';
                                            echo $gets;
                                            echo '</li>';
                                        }
                                        echo '</ul>';
                                    }
                                    ?></span>
                            </li>
                            <li>
                                <span title="what user gets"></span><span class="package-headers"> WHAT USER GETS<br/></span><span class="package-text"><?php
                                    if (!empty($package[0]['whatuserget'])) {
                                        $userGetsArr = explode(',', $package[0]['whatuserget']);
                                        echo '<ul>';
                                        foreach ($userGetsArr as $gets) {
                                            echo '<li>';
                                            echo $gets;
                                            echo '</li>';
                                        }
                                        echo '</ul>';
                                    }
                                    ?></span>
                            </li>
                        </ul> 

                        </li>
                        <li>
                            <?php
                            if ($package[0]['image_path']) {
                                $packagePathArr = explode('/', $package[0]['image_path']);
                                foreach ($packagePathArr as $imageName) {
                                    $imageFile = $imageName;
                                }
                                ?>
                                <img alt="Subject Image" src="<?php echo $_SESSION['basedomain']['path'] . '/data/images/' . $imageFile; ?>" style="height:auto; width: 25%;border-radius: 50%;"/>
                            <?php } ?>
                        </li>
                    </ul>  
                </div>
                <div id="two">
                    
                    <a href="javascript:void(0)" class="wpcf7-form-control wpcf7-submit demo-chapter">

                        <input type="button" value="BUY NOW" class="wpcf7-form-control wpcf7-submit" id="buy"></a>
                </div>
            </div>
        </div> 
    </div>
    <div id="form-footer">
    </div>
</div>

<script>
    var blogpopup = {};
    blogpopup = {
        'baseurl': '<?php echo 'http://' . $_SERVER['HTTP_HOST'] . $this->url('home') ?>',
        openpopup: function () {
            $('#koolguru-pop').click();
        },
        setpopuptitle: function (title) {
            $('#poptitle').text('');
            $('#poptitle').text(title);
        },
        setpopupmsg: function (msg) {
            $('#pop-msg').text('');
            $('#pop-msg').text(msg);
        },
        popupclose: function () {
            $('#pop-close').click();
        },
        createpopupfooterbtn: function () {
            var _this = this;
            var btnstr = '';
            btnstr += "&nbsp;<input id='loginbtn' type='button' class='green-btn pop-btn margin-Top10-Btm40' value='Log In'>";
            btnstr += "&nbsp;<input id='cancel' type='button' class='green-btn pop-btn margin-Top10-Btm40' value='Cancel'>";
            $('#pop-footer').html(btnstr);
            $('#cancel').click(function () {
                _this.popupclose();
            });

            $('#loginbtn').click(function () {
                var redirecturl = _this.baseurl + 'studentlogin?redirect=1';
                window.location.assign(redirecturl);
            });
        },
        createclosefooterbtn: function () {
            var _this = this;
            var btnstr = '';
            btnstr += "&nbsp;<input id='cancel' type='button' class='green-btn pop-btn margin-Top10-Btm40' value='Close'>";
            $('#pop-footer').html(btnstr);
            $('#cancel').click(function () {
                _this.popupclose();
            });
        }
    }
    app.blogpopup = blogpopup;
    $('#buy').on('click', function () {
        var url = '<?php echo $this->basePath() . '/checklogin'; ?>';
        $.ajax({url: url, success: function (result) {
                if (result == 1) {
                    var id = $('#packageId').val();
                    var url = '<?php echo $this->basePath() . '/application/index/initiatetransaction?id='; ?>' + id;
                    $.ajax({url: url, success: function (result) {
                            var _this = this;
                            var redirecturl = '<?php echo $this->basePath() . '/application/index/userpay?id='; ?>' + id;
                            window.location.assign(redirecturl);
                        }});
                } else {
                    app.blogpopup.setpopuptitle('Confirmation');
                    app.blogpopup.setpopupmsg('To complete purchase, you need to login first');
                    app.blogpopup.createpopupfooterbtn();
                    app.blogpopup.openpopup();
                }
            }});
    });
</script>







