<?php
if (isset($_SESSION['User']['roleCode'])):
    $roleCode = $_SESSION['User']['roleCode'];
endif;
?>
<section class="sub-header">
    <div class="container">
        <div class="sub-header-title">
            <?php
            $title = 'Package Details';
            $this->headTitle($title);
            ?>
            <h1 class="h1"><?php echo $this->escapeHtml($title); ?>

                <?php
                /* Adding Breadcrumb */
                echo $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                ?>
            </h1>
        </div>
    </div>
</section>

<div class="container">
    <div class="forms">
        <div class="container">
                <div class="package_detail_left">
                    <ul>
                        <li class="name detail-row package-header">
                            <?php echo $package[0]['title']; ?>
                            <span class="separator-img"></span>
                            <span class="buy-course"><a href="javascript:void(0)">BUY NOW</a></span>
                        </li>
                        <li class="nid detail-row">
                            <span class="nid-icon" title="relevant for"></span><span class="detail"> RELEVANT FOR : <?php
                                if (!empty($package[0]['relevant_for'])) {
                                    $userGetsArr = explode(',', $package[0]['relevant_for']);
                                    echo '<br/>';
                                    echo '<ul>';
                                    foreach ($userGetsArr as $gets) {
                                        echo '<li>';
                                        echo $gets;
                                        echo '</li>';
                                    }
                                    echo '</ul>';
                                }
                                ?></span>
                        </li>
                        <li class="nid detail-row">
                            <?php
                            if ($package[0]['image_path']) {
                                $packagePathArr = explode('/', $package[0]['image_path']);
                                foreach ($packagePathArr as $imageName) {
                                    $imageFile = $imageName;
                                }
                                ?>
                                <img alt="Subject Image" src="<?php echo $_SESSION['basedomain']['path'] . '/data/images/' . $imageFile; ?>" style="height:auto; width: 25%;border-radius: 50%;"/>
                            <?php } ?>
                        </li>
                    </ul>  
                </div> 
                <div class="package_detail_right">
                    <ul>

                        <li class="nid detail-row">
                            <span class="nid-icon" title="Duration"></span><span class="detail"> DURATION : <?php echo $package[0]['duration'] ?></span>
                        </li>
                        <li class="nid detail-row">
                            <span class="nid-icon" title="Price"></span><span class="detail"> PRICE : <?php echo $package[0]['price'] ?></span>
                        </li>
                        <li class="nid detail-row">
                            <span class="nid-icon" title="Face to Face Class-room"></span><span class="detail"> FACE TO FACE CLASSROOM : <?php echo $package[0]['ff_classroom'] ?></span>
                        </li>
                        <li class="nid detail-row">
                            <span class="nid-icon" title="advantage"></span><span class="detail"> ADVANTAGE : <?php
                                if (!empty($package[0]['advantage'])) {
                                    $userGetsArr = explode(',', $package[0]['advantage']);
                                    echo '<br/>';
                                    echo '<ul>';
                                    foreach ($userGetsArr as $gets) {
                                        echo '<li>';
                                        echo $gets;
                                        echo '</li>';
                                    }
                                    echo '</ul>';
                                }
                                ?></span>
                        </li>
                        <li class="nid detail-row">
                            <span class="nid-icon" title="what user gets"></span><span class="detail"> WHAT USER GETS : <?php
                                if (!empty($package[0]['whatuserget'])) {
                                    $userGetsArr = explode(',', $package[0]['whatuserget']);
                                    echo '<br/>';
                                    echo '<ul>';
                                    foreach ($userGetsArr as $gets) {
                                        echo '<li>';
                                        echo $gets;
                                        echo '</li>';
                                    }
                                    echo '</ul>';
                                }
                                ?></span>
                        </li>
                    </ul> 
                </div>
        </div>
    </div>
    <div id="form-footer">
    </div>
</div>









