<div class="staff">
    <div class="reservation_top">
        <div class="container">          	 
            <h3 class="hist"></h3>
            <div class="row">
                <?php if(!empty($testimonials)){?>
                    <?php foreach($testimonials as $testi){?>
                    <div style="height: 300px;">
                                <div style="padding-left:5px;padding-top:5px; ;width:20%;float:left;">
                                    <img src="<?php echo $this->basePath() . '/img/'.$testi['image'];?>" alt=""/>
                                    <div style="margin-top:5px;margin-left:5px ;color: #aaa;font-size: 14px;text-align: left;font-family: poppins;">
                                        <?php echo $testi['name'];?>
                                    </div>
                                    <div style="margin-top:5px;margin-left:5px;color: #aaa;font-size: 14px;text-align: left;font-family: poppins;">
                                        <?php echo $testi['degree'];?>
                                    </div>
                                </div>

                                <div style="margin-left: 250px;padding-top: 5px;padding-right: 5px;font-size: 14px;text-align: left;font-family: poppins;">
                                    <?php echo $testi['description'];?>
                                </div>
                            </div>
                            

                    <?php }} ?>
                
            </div>
        </div>
    </div>
</div>