<div class="staff">
    <div class="reservation_top">
        <div class="container">          	 
            <h3 class="hist">Vision</h3>
            <div class="row">
                <div class="col-sm-6">
                    <img src="<?php echo $this->basePath() . '/img/h1.jpg' ?>" class="img-responsive" alt=""/>
                </div>
                <div class="col-sm-6 history_grid">
<!--                    <h3><a href="#">Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl</a></h3>-->
                    <p>We envision to revolutionize the education making it more greener, affordable and result-oriented.</p>
                                    <a href="#" title="Online Reservation" class="btn btn-primary btn2 btn-normal btn-inline " target="_self">Read More</a>
                </div>
            </div>
        </div>
    </div>
</div>