<style>

</style>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('student', array('action' => 'studentregistration')));
$form->setAttribute('class', 'detect_changes');
$form->prepare();
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
//asd($errorflashMessage);
?>

<div class="main"> 
    <div class="reservation_top">
        <div class="container">
            <main>
                <input id="tab1" type="radio" name="tabs" checked class="tab-radio">
                <label for="tab1">Personal Detail</label>

                <input id="tab2" type="radio" name="tabs" class="tab-radio">
                <label for="tab2">Verbal Ability</label>

                <input id="tab3" type="radio" name="tabs" class="tab-radio">
                <label for="tab3">Quantitative Ability</label>

                <input id="tab4" type="radio" name="tabs" class="tab-radio">
                <label for="tab4">Carrier Oriented Question</label>

                <?php echo $this->form()->openTag($form); ?>
                <div class="container">
                    <div class="forms" id="student-registration-form">
                        <section id="basic_details">
                            <h2 class='h2'>Basic Details</h2>
                            <ul>
                                <li class="form-row">
                                    <label class='label'>First Name:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('fname'));
                                    echo $this->formElement($form->get('student_id'));
                                    ?>
                                </li>
                                <li class="form-row">
                                    <label class='label'>Middle Name:</label>
                                    <?php
                                    echo $this->formElement($form->get('mname'));
                                    ?>
                                </li>
                                <li class="form-row">
                                    <label class='label'>Last Name:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('lname'));
                                    ?>
                                </li>
                                <li class="form-row">
                                    <label class='label'>Gender:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('sex'));
                                    ?>
                                </li>

                                <li class="form-row">
                                    <label class='label'>Father Occupation:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('father_occupation'));
                                    ?>
                                </li>

                                <li class="form-row">
                                    <label class='label'>Highest Degree:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('highest_degree'));
                                    ?>
                                </li>

                                <li class="form-row">
                                    <label class='label'>Completion Year:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('completion_year'));
                                    ?>
                                </li>

                                <li class="form-row">
                                    <label class='label'>Native State:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('native_state'));
                                    ?>
                                </li>

                                <li class="form-row">
                                    <label class='label'>City:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('city'));
                                    ?>
                                </li>

                                <li class="form-row">
                                    <label class='label'>Mobile:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('mobile'));
                                    ?>
                                </li>

                                <li class="form-row">
                                    <label class='label'>Email:<span class='required'>*</span></label>
                                    <?php
                                    echo $this->formElement($form->get('email'));
                                    ?>
                                </li>
                            </ul>
                            <div class="form-footer">
                                <?php
                                echo $this->formInput($form->get('regsubmit'));
                                echo $this->form()->closeTag();
                                ?>
                            </div>
                        </section>
                    </div>
                </div>

                
                <?php if ($enableTabContent[1]) { ?>
                    <form action="/myapp/koolguruweb/public/student/studentregistration" method="post" name="user-verbal" class="detect_changes" id="user-verbal">
                        <input type='hidden' name='student_id' id='student_id' value='<?php echo $student_id;?>'>
                        <div class="container">
                        <div class="forms" id="student-registration-verbal">
                        <section id="basic_details">
                            <h2 class="h2">Verbal Ability</h2>
                            
                            <?php $i = 1;foreach ($verbalQuestions as $ky => $quest) {//asd($quest);?>
                                <div class="questionborder" style='margin-top:10px'>
                                    <span class="badge pull-left"><?php echo $i; ?></span>
                                    <h4 class="questiontitle"><?php echo $quest['title']; ?></h4>
                                    <div class="book_date btm">
                                        <ul>
                                            <?php foreach ($quest['options'] as $key => $options) { 
                                                if($key == ($quest['correct']-1) ){
                                                    $val = $quest['maxmark'];
                                                }else{
                                                    $val = $quest['minmark'];
                                                }
                                                ?>
                                                <li class="form-row">                                     
                                                    <label class="custom-label" onclick="">
                                                        <input type="radio" name="<?php echo $ky; ?>" id="<?php echo $ky . '-' . $key; ?>" value="<?php echo $val.'~'.($key+1).'~'.$quest['maxmark'];?>" style="position: absolute; left: -9999px;">
                                                        <?php echo $options;?></label>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                </div>
                            <?php $i++;} ?>
                            <div class="form-footer">
                            <?php if(!empty($studentStatus) && isset($studentStatus[0]['verbal_reg_status']) && $studentStatus[0]['verbal_reg_status']==1){?>
                            <?php }else{?>
                            <input name="verbalsubmit" type="submit" id="verbalsubmit" class="green-btn big-btn margin-Top10-Btm40" value="Submit">                            </div>
                            <?php } ?>
                        </section>
                    </div>
                </div></form>
                
                
                
                
                
                
                <?php } ?>
                
                
                
                

                <section id="content3">
<?php if ($enableTabContent[2]) { ?>
                        <p>
                            Bacon ipsum dolor sit amet beef venison beef ribs kielbasa. Sausage pig leberkas, t-bone sirloin shoulder bresaola. Frankfurter rump porchetta ham. Pork belly prosciutto brisket meatloaf short ribs.
                        </p>
                        <p>
                            Brisket meatball turkey short loin boudin leberkas meatloaf chuck andouille pork loin pastrami spare ribs pancetta rump. Frankfurter corned beef beef tenderloin short loin meatloaf swine ground round venison.
                        </p>
<?php } ?>
                </section>

                <section id="content4">
<?php if ($enableTabContent[3]) { ?>
                        <p>
                            Bacon ipsum dolor sit amet landjaeger sausage brisket, jerky drumstick fatback boudin ball tip turducken. Pork belly meatball t-bone bresaola tail filet mignon kevin turkey ribeye shank flank doner cow kielbasa shankle. Pig swine chicken hamburger, tenderloin turkey rump ball tip sirloin frankfurter meatloaf boudin brisket ham hock. Hamburger venison brisket tri-tip andouille pork belly ball tip short ribs biltong meatball chuck. Pork chop ribeye tail short ribs, beef hamburger meatball kielbasa rump corned beef porchetta landjaeger flank. Doner rump frankfurter meatball meatloaf, cow kevin pork pork loin venison fatback spare ribs salami beef ribs.
                        </p>
                        <p>
                            Jerky jowl pork chop tongue, kielbasa shank venison. Capicola shank pig ribeye leberkas filet mignon brisket beef kevin tenderloin porchetta. Capicola fatback venison shank kielbasa, drumstick ribeye landjaeger beef kevin tail meatball pastrami prosciutto pancetta. Tail kevin spare ribs ground round ham ham hock brisket shoulder. Corned beef tri-tip leberkas flank sausage ham hock filet mignon beef ribs pancetta turkey.
                        </p>
<?php } ?>
                </section>

            </main>
            <div class="row">                
                <div class="col-md-7 contact_right">


                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var tab = new Array();
        tab = [<?php echo '"' . implode('","', $enableTab) . '"' ?>];
        app.studentTab.enabletab = tab;
        app.studentTab.applytabbing(app.studentTab.enabletab);
    });
</script>
