<?php
$form = $this->form;
$form->setAttribute('action', $this->url('student', array('action' => 'studentregistration')));
$form->setAttribute('class', 'detect_changes');
$form->prepare();
$errorflashMessage = $this->flashMessenger()->getErrorMessages();
//asd($errorflashMessage);
?>

<div class="main"> 
    <div class="reservation_top">
        <div class="container">
            <main>

                <label for="tab1" id='tab-1' class="kooltab" onclick="app.studentTab.openTag(1)">Personal Detail</label>                
                <label for="tab2" id='tab-2' class="kooltab" onclick="app.studentTab.openTag(2)"><span>Verbal Ability</span></label>                
                <label for="tab3" id='tab-3' class="kooltab" onclick="app.studentTab.openTag(3)">Quantitative Ability</label>                
                <label for="tab4" id='tab-4' class="kooltab" onclick="app.studentTab.openTag(4)">Carrier Oriented Question</label>

                <?php echo $this->form()->openTag($form); ?>
                <div class="tabs" id='content-1'>
                    <div class="container">
                        <div class="forms" id="student-registration-form">
                            <section id="basic_details">
                                <h2 class='h2'>Basic Details</h2>
                                <ul>
                                    <li class="form-row">
                                        <label class='label'>First Name:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('fname'));
                                        echo $this->formElement($form->get('student_id'));
                                        ?>
                                    </li>
                                    <li class="form-row">
                                        <label class='label'>Middle Name:</label>
                                        <?php
                                        echo $this->formElement($form->get('mname'));
                                        ?>
                                    </li>
                                    <li class="form-row">
                                        <label class='label'>Last Name:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('lname'));
                                        ?>
                                    </li>
                                    <li class="form-row">
                                        <label class='label'>Gender:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('sex'));
                                        ?>
                                    </li>

                                    <li class="form-row">
                                        <label class='label'>Father Occupation:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('father_occupation'));
                                        ?>
                                    </li>

                                    <li class="form-row">
                                        <label class='label'>Highest Degree:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('highest_degree'));
                                        ?>
                                    </li>

                                    <li class="form-row">
                                        <label class='label'>Completion Year:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('completion_year'));
                                        ?>
                                    </li>

                                    <li class="form-row">
                                        <label class='label'>Native State:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('native_state'));
                                        ?>
                                    </li>

                                    <li class="form-row">
                                        <label class='label'>City:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('city'));
                                        ?>
                                    </li>

                                    <li class="form-row">
                                        <label class='label'>Mobile:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('mobile'));
                                        ?>
                                    </li>

                                    <li class="form-row">
                                        <label class='label'>Email:<span class='required'>*</span></label>
                                        <?php
                                        echo $this->formElement($form->get('email'));
                                        ?>
                                    </li>
                                </ul>
                                <div class="form-footer">
                                    <?php
                                    echo $this->formInput($form->get('regsubmit'));
                                    echo $this->form()->closeTag();
                                    ?>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>

                <!-- Tab for verbal ability -->
                <div class="tabs" id='content-2'>
                    <?php if ($enableTabContent[1]) { ?>
                    <form action="/myapp/koolguruweb/public/student/studentregistration" method="post" name="user-verbal" class="detect_changes" id="user-verbal">
                        <input type='hidden' name='student_id' id='student_id' value='<?php echo $student_id; ?>'>
                        <div class="container">
                            <div class="forms" id="student-registration-verbal">
                                <section id="basic_details">
                                    <h2 class="h2">Verbal Ability</h2>                            
                                    <?php $i = 1;
                                    foreach ($verbalQuestions as $ky => $quest) {//asd($quest); ?>
                                        <div class="questionborder" style='margin-top:10px'>
                                            <span class="badge pull-left"><?php echo $i; ?></span>
                                            <h4 class="questiontitle"><?php echo $quest['title']; ?></h4>
                                            <div class="book_date btm">
                                                <ul>
                                                    <?php
                                                    foreach ($quest['options'] as $key => $options) {
                                                        if ($key == ($quest['correct'])) {
                                                            $val = $quest['maxmark'];
                                                        } else {
                                                            $val = $quest['minmark'];
                                                        }
                                                        ?>
                                                        <li class="form-row">                                     
                                                            <label class="custom-label" onclick="">
                                                                <input type="radio" name="<?php echo $ky; ?>" id="<?php echo $ky . '-' . $key; ?>" value="<?php echo $val . '~' . ($key) . '~' . $quest['maxmark']; ?>" style="position: absolute; left: 173px;">
                                                                <span style="position: absolute; left: 200px;"><?php echo $options; ?><span></label>
                                                        </li>
        <?php } ?>
                                                </ul>
                                            </div>
                                        </div>
                                            <?php $i++;
                                        } ?>
                                    <div class="form-footer">
                                    <?php if (!empty($studentStatus) && isset($studentStatus[0]['verbal_reg_status']) && $studentStatus[0]['verbal_reg_status'] == 1) { ?>
                                    <?php } else { ?>
                                            <input name="verbalsubmit" type="submit" id="verbalsubmit" class="green-btn big-btn margin-Top10-Btm40" value="Submit">                            </div>
                                    <?php } ?>
                                </section>
                            </div>
                        </div>
                    </form>
<?php } ?>
                </div>
                
                <!-- Tab for verbal ability -->
                <div class="tabs" id='content-3'>
                    <?php if ($enableTabContent[2]) { ?>
                        <form action="/myapp/koolguruweb/public/student/studentregistration" method="post" name="user-verbal" class="detect_changes" id="user-verbal">
                        <input type='hidden' name='student_id' id='student_id' value='<?php echo $student_id; ?>'>
                        <div class="container">
                            <div class="forms" id="student-registration-verbal">
                                <section id="basic_details">
                                    <h2 class="h2">Quantitative Ability</h2>                            
                                    <?php $i = 1;
                                    foreach ($quantQuestions as $ky => $quest) {//asd($quest); ?>
                                        <div class="questionborder" style='margin-top:10px'>
                                            <span class="badge pull-left"><?php echo $i; ?></span>
                                            <h4 class="questiontitle"><?php echo $quest['title']; ?></h4>
                                            <div class="book_date btm">
                                                <ul>
                                                    <?php
                                                    foreach ($quest['options'] as $key => $options) {
                                                        if ($key == ($quest['correct'])) {
                                                            $val = $quest['maxmark'];
                                                        } else {
                                                            $val = $quest['minmark'];
                                                        }
                                                        ?>
                                                        <li class="form-row">                                     
                                                            <label class="custom-label" onclick="">
                                                                <input type="radio" name="<?php echo $ky; ?>" id="<?php echo $ky . '-' . $key; ?>" value="<?php echo $val . '~' . ($key) . '~' . $quest['maxmark']; ?>" style="position: absolute; left: 173px;">
                                                                <span style="position: absolute; left: 200px;"><?php echo $options; ?><span></label>
                                                        </li>
        <?php } ?>
                                                </ul>
                                            </div>
                                        </div>
                                            <?php $i++;
                                        } ?>
                                    <div class="form-footer">
                                    <?php if (!empty($studentStatus) && isset($studentStatus[0]['quant_status']) && $studentStatus[0]['quant_status'] == 1) { ?>
                                    <?php } else { ?>
                                            <input name="quantsubmit" type="submit" id="quantsubmit" class="green-btn big-btn margin-Top10-Btm40" value="Submit">                            </div>
                                    <?php } ?>
                                </section>
                            </div>
                        </div>
                    </form>
                    <?php } ?>
                </div>

                
                <div class="tabs" id='content-4'>
                        <?php if ($enableTabContent[3]) { ?>
                        <p>
                            Bacon ipsum dolor sit amet beef venison beef ribs kielbasa. Sausage pig leberkas, t-bone sirloin shoulder bresaola. Frankfurter rump porchetta ham. Pork belly prosciutto brisket meatloaf short ribs.
                        </p>
                        <p>
                            Brisket meatball turkey short loin boudin leberkas meatloaf chuck andouille pork loin pastrami spare ribs pancetta rump. Frankfurter corned beef beef tenderloin short loin meatloaf swine ground round venison.
                        </p>
                    <?php } ?>
                </div>
            </main>            
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var tab = new Array();
        var enabletabcontent = new Array();
        tab = [<?php echo '"' . implode('","', $enableTab) . '"' ?>];
        enabletabcontent = [<?php echo '"' . implode('","', $enableTabContent) . '"' ?>];        
        app.studentTab.enabletab = tab;   
        app.studentTab.enabletabcontent = enabletabcontent;
        
        $('.kooltab').each(function(){
            var tabid = $(this).attr('id');
            tabid = tabid.replace("tab-", "");
            app.studentTab.hidetab(parseInt(tabid));
        });
        
        console.log(app.studentTab);
        //console.log(app.studentTab.enabletabcontent);
        $.each(app.studentTab.enabletabcontent, function( index, value ) {            
            if(value == 1){
                $('#tab-'+(index+1)).addClass('enabletab');
                $('#tab-'+(index+1)).click();
            }
        });
        
        $.each(app.studentTab.enabletab, function( index, value ) {            
            if(value == 1){
                $('#tab-'+(index+1)).addClass('activetab');
            }
        });
        

        
//        app.studentTab.hidetab(1);
//        app.studentTab.hidetab(2);
//        app.studentTab.hidetab(3);
//        app.studentTab.hidetab(4);
//        app.studentTab.applytabbing(app.studentTab.enabletab);
//        app.studentTab.enableTabContent();
    });
</script>
